### ISSUE TITLE
List all supported languages

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#102]
We would like to add a command line flag to display all supported languages,
Something like:

`onefetch -s (--support)`

:100: :1st_place_medal:

**Comment by mkrl** [comment]
I'd like to give it a go. A good chance to do some Rust 👍

**Comment by vypxl** [comment]
@mkrl sry I didn't see you, I already did it whoops. Maybe should have called myself out. I'm sorry

**Comment by mkrl** [comment]
No problem, whatever works. Great job @vypxl

**Comment by vypxl** [comment]
Thanks and sorry again @mkrl
