### ISSUE TITLE
Please bump git2

### ISSUE THREAD

**Issue by 0323pin** [o2sh/onefetch#1025]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

`onefetch` no longer builds on NetBSD, since we have updated `libgit2` to 1.6.4 and `onefetch` still depends on `git2` 0.16 that pulls `libgit2-sys` 1.5.1 causing a mismatch with the installed `libgit2`.

Please bump `git2` to 0.17.1 that uses `libgit2-sys` 1.6.4

Thanks!

**Comment by spenserblack** [comment]
@o2sh Thoughts? Patch release for NetBSD compatibility?

@0323pin Could you provide some insight into how Rust projects are typically built for NetBSD? I'm assuming you use a pre-built binary. Are the exact dependencies from `Cargo.lock` used? Just wondering if a broader version range like `>= 0.16, < 0.18` would be of any help.

If I'm not mistaken, I think we can also enable the `vendored-libgit2` feature to use a version of `libgit2` vendored by the `git2-sys` crate instead of whatever is installed on the system.

**Comment by 0323pin** [comment]
@spenserblack Thanks.

We have had our share of issues with `libgit2`, https://github.com/libgit2/libgit2/issues/6457 and https://github.com/libgit2/libgit2/pull/6458

But, the issues are now fixed. We have waited for a while to merge it, since it breaks quite a few Rust packages. Now, we have decided it was time. We have patched the Rust packages that were still using the old version and only two are still a problem, `onefetch` and `gerb`.

> Could you provide some insight into how Rust projects are typically built for NetBSD?

The packages are build with `cargo` locked and offline.

> Just wondering if a broader version range like >= 0.16, < 0.18 would be of any help.

It will use whatever `Cargo.lock` defines.

Please don't enable the vendored feature, we prefer not to.

The following patch fixes the build on 7be7ea92a29117706af73f4ff9799a9a5a3d76b1

```
--- Cargo.toml.orig	2023-04-26 18:52:59.000000000 +0000
+++ Cargo.toml
@@ -29,7 +29,7 @@ gix-features-for-configuration-only = { 
 gix = { version = "0.44.0", default-features = false, features = [
     "max-performance-safe",
 ] }
-git2 = { version = "0.16.1", default-features = false }
+git2 = { version = "0.17.1", default-features = false }
 human-panic = "1.1.0"
 image = "0.24.6"
 num-format = "0.4.4"
```

Of course, also patching `Cargo.lock`.

**Comment by spenserblack** [comment]
#1030

**Comment by spenserblack** [comment]
Also, just an FYI that [we're hoping to eventually drop libgit2 as a dependency](https://github.com/o2sh/onefetch/issues/628).

**Comment by 0323pin** [comment]
> Also, just an FYI that [we're hoping to eventually drop libgit2 as a dependency](https://github.com/o2sh/onefetch/issues/628).

That would also be a solution 😃

**Comment by o2sh** [comment]
Thanks @0323pin for bringing this to our attention and for maintaining the package on NetBSD. 

The git2 dependency is now up to date.

Thanks @spenserblack for merging some of the dependabot backlog, I completely forgot about the 5 PR limit 😓 

We can maybe keep this issue open until the next release. BTW, @0323pin did you find a workaround? or do you need a new release asap?

**Comment by o2sh** [comment]
[2.17.1](https://github.com/o2sh/onefetch/releases/tag/2.17.1)  is out 🎉
