### ISSUE TITLE
Can't install onefetch

### ISSUE THREAD

**Issue by krax1337** [o2sh/onefetch#1032]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Trying to install onefetch and got this error.

`cargo install onefetch`

```
    Updating crates.io index
  Installing onefetch v2.17.0
error: failed to compile `onefetch v2.17.0`, intermediate artifacts can be found at `/tmp/cargo-installaLVAdH`

Caused by:
  failed to select a version for the requirement `gix = "^0.36.1"`
  candidate versions found which didn't match: 0.44.1, 0.43.1, 0.42.0, ...
  location searched: crates.io index
  required by package `onefetch v2.17.0`
```

### Expected behavior 🤔

Installed onefetch.

### Steps to reproduce 🕹

1. cargo install onefetch

### Additional context/Screenshots 🔦

![изображение](https://user-images.githubusercontent.com/20024303/235184246-2d695a21-f7f1-4a5c-a756-2abc85b58218.png)

**Comment by spenserblack** [comment]
This has probably been resolved, since we've updated the dependency in `Cargo.toml` :slightly_smiling_face:
Would you be able to build from `main`?
https://github.com/o2sh/onefetch/blob/15db60556ccceecd170f2b0d964ae11ad46e1810/Cargo.toml#L29

**Comment by spenserblack** [comment]
Just did a quick review, looks like `gix@0.36.1` was yanked. You could possibly install an earlier version of onefetch with `cargo install --version 2.15.0 onefetch`. I think that's the last released version at the moment that didn't use the yanked version of `gix` (because it used the old crate name for `gix`).

**Comment by o2sh** [comment]
Thanks for bringing to our attention @krax1337 

>Just did a quick review, looks like gix@0.36.1 was yanked

Ouch! 😟 Seems like a good time to publish a new release 😅

**Comment by o2sh** [comment]
@krax1337  [2.17.1 is out](https://github.com/o2sh/onefetch/releases/tag/2.17.1)

You can try running `cargo install onefetch` again, it should be good now 👍

**Comment by krax1337** [comment]
Thank you for fast feedback, now it's fine 👍❤️
