### ISSUE TITLE
Code in subdirectory

### ISSUE THREAD

**Issue by sascha-andres** [o2sh/onefetch#1055]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Currently I do get an error when changing to my SQL repository:

    Error: Could not find any source code in this repository

### Expected behavior 🤔

Show SQL as code

### Steps to reproduce 🕹

Create a git repository with this layout:

    …/test on  main 🐟 ✓  tree
    .
    ├── README.md
    └── subdir
        └── test.sql
    
    2 directories, 2 files

Change to that directory

**Comment by sascha-andres** [comment]
Actually created above repo as repro, version 2.17.1

**Comment by spenserblack** [comment]
Right now SQL is marked as data, not a programming language, so it has to be explicitly shown with a CLI option.

If there's further confusion, perhaps it should be marked as a programming language :thinking:

**Comment by sascha-andres** [comment]
Depends on your use case. In my case it is a historic collection of administrative statements and queries for data (re)search.

If you do a lot of procedures and/or triggers SQL can be viewed as a programming language (differing in dialect, though)

As I can go with passing -T easily and this is opinionated, I will close this ticket with this comment
