### ISSUE TITLE
Display git version + username

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#106]
On top of the repository infos, we would like to show general information (not specific to the repo), like git username (git config user.name) and the version of Git installed on the machine (git --version). Something like -->

![Untitled](https://user-images.githubusercontent.com/13710835/67389745-7c8f1a80-f59b-11e9-943c-bf115685469c.png)

💯 🥇

**Comment by pablodiegoss** [comment]
I've tried to replicate your prototype on #107, what do you think?
![Screenshot from 2019-10-23 11-12-51](https://user-images.githubusercontent.com/8556291/67401847-177cfa00-f586-11e9-8b55-f0927c6c1be8.png)

**Comment by o2sh** [comment]
Great start @pablodiegoss 

Few remarks:
* The dotted line has to match the length of the displayed info, in this case: _Pablo Diego: git version_ 2.20.1
* You have to handle the case where the git username is unknown --> Don't print ":" at the start

Looking forward to merge your PR 👍

**Comment by pablodiegoss** [comment]
Nice!
I'll work on those remarks then :)

**Comment by pablodiegoss** [comment]
After formatting the line and username case it looks like this

With username:
![Screenshot from 2019-10-23 12-17-33](https://user-images.githubusercontent.com/8556291/67408432-56fc1400-f58f-11e9-805a-a5d1242bfa47.png)

And without:
![Screenshot from 2019-10-23 12-18-30](https://user-images.githubusercontent.com/8556291/67408440-59f70480-f58f-11e9-93d0-43015470a043.png)

**Comment by o2sh** [comment]
Looking better @pablodiegoss 

Last remarks:

* The text has to be diplayed in bold (except the dotted line), you should check #99 (already merged) to make sure that we can disable boldness on your text too
* We can't see it in your example, but the text should be displayed in color (like the info titles); by text I don't include **the dotted line and the separator** --> only git username and git version

🥇

**Comment by pablodiegoss** [comment]
I've updated the color and bold o/
![Screenshot from 2019-10-24 12-22-34](https://user-images.githubusercontent.com/8556291/67500426-05b85700-f659-11e9-874c-84ef3269e64a.png)

**Comment by pablodiegoss** [comment]
I'm not quite sure how to do that, because the `write_buf` function that prints and paint texts breaks a line after printing something. So if i leave the ":" as white the next printed text with the git version will be in a new line. If i change the `write_buf`to not break lines, all the code should be changed to add line breaks.
Should i create another `write_buf` just for that line break?

**Comment by pablodiegoss** [comment]
Sorry, forgot about the separator, should be fine now.
