### ISSUE TITLE
Chore: add branch protections/rulesets to `main` branch

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#1087]
I don't think they've been set, since I don't see that little shield icon that protected branches have :laughing:

I've accidentally pushed to this repo's `main` branch when I've meant to push to my fork's `main` branch, so at the very least this will give me and other collaborators a bit of peace of mind.

But also, enabling branch protections like "require approval before merge" and "require checks to pass before merge" enables the auto-merge feature on PRs, which will allow you to mark a PR as ready to merge in advance, but the actual merge still waits until all requirements have passed. This can be pretty helpful since our CI can take quite a long time :laughing: Instead of revisiting a PR once the CI has passed, you can queue up a merge if the PR looks good and let it happen automatically.

**Comment by o2sh** [comment]
Thanks for the heads up @spenserblack 

I've added a ruleset to the main branch. You can check it out here: https://github.com/o2sh/onefetch/rules/35779?ref=refs%2Fheads%2Fmain

Please let me know if I missed anything

**Comment by spenserblack** [comment]
Thanks!

**Comment by o2sh** [comment]
Just realized that [Generate language badge](https://github.com/o2sh/onefetch/actions/workflows/language-badge.yml) and [Generate MSRV Badge](https://github.com/o2sh/onefetch/actions/workflows/msrv-badge.yml) won't work anymore since they were designed to commit directly to the main branch. We might need to update them to create a pull request instead.

---------------------
On a side note I also enabled "auto-merge" for pull request

**Comment by spenserblack** [comment]
> Just realized that [Generate language badge](https://github.com/o2sh/onefetch/actions/workflows/language-badge.yml) and [Generate MSRV Badge](https://github.com/o2sh/onefetch/actions/workflows/msrv-badge.yml) won't work anymore since they were designed to commit directly to the main branch

Good point, I completely forgot about those :laughing:
A workaround may be to use a PAT for those actions :thinking:

Otherwise, if you want to go the PR route, we can get fancy and close stale PRs too by identifying them with labels.

**Comment by o2sh** [comment]
PAT added [63a171c](https://github.com/o2sh/onefetch/commit/63a171c10a3264db0f6ad17a8628c51c034c9762)

Seems to work [83dbce5](https://github.com/o2sh/onefetch/commit/83dbce54686662404a49d141bbbb8b9a4a3aa65d)

Thanks @spenserblack

**Comment by spenserblack** [comment]
Thanks!
