### ISSUE TITLE
Errs when invoked on partial clones

### ISSUE THREAD

**Issue by icp1994** [o2sh/onefetch#1092]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

```sh
$ git clone --filter=blob:none https://github.com/sharkdp/fd
$ onefetch fd/
Error: sending on a closed channel
```

### Expected behavior 🤔

I don't know if [partial clones](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) have some limitations which prevents onefetch from working so maybe erring is the expected behavior.

**Comment by icp1994** [comment]
Possible duplicate/related https://github.com/o2sh/onefetch/issues/978. Also, onefetch 2.18.0

**Comment by spenserblack** [comment]
Would you be willing to try out an earlier version? I'm curious if this was introduced in the recently released version.

**Comment by icp1994** [comment]
Works with v2.17.1

**Comment by spenserblack** [comment]
Thanks for checking!

The fact that it was introduced in v2.18, along with this error

> ```
> Error: sending on a closed channel
> ```

Makes me think that this was introduced with our new file churn metric.

**Comment by icp1994** [comment]
https://github.com/o2sh/onefetch/commit/d5f86216c596b56940f80c97fdb8635c3be640bf is the last "good" commit. With the next commit https://github.com/o2sh/onefetch/commit/1955153a9f998780b78bc391df1a94464c57cc80 I get:
```
Error: Could not find blob for similarity checking

Caused by:
    An object with id 0da0e9c3963daf5e99f99d2adbf825ce15090c58 could not be found
```
Same with https://github.com/o2sh/onefetch/commit/fd1d5f04bbf1fbf160506fad4a05dd2b1dd35fd9 and finally after the following commit https://github.com/o2sh/onefetch/commit/09c4dc9df6e1201eeed54b01f3432f4097ff54dc it shows the current error.

**Comment by spenserblack** [comment]
Thanks for bisecting and finding the exact commits!

**Comment by o2sh** [comment]
@icp1994 new release with a fix -> https://github.com/o2sh/onefetch/releases/tag/2.18.1

**Comment by icp1994** [comment]
Thanks! Tested locally, works as intended.
