### ISSUE TITLE
Make Debian packages

### ISSUE THREAD

**Issue by arf20** [o2sh/onefetch#1125]
### Summary 💡

Distribute a Debian package. This is far more universal for all Debian based distros.
Currently you only support a Ubuntu ppa. Making Debian packages would work for Ubuntu and all other Debian based distros.

### Motivation 🔦

Debian stable being slightly behind in rustc version, and rust being so picky with compiler versions.

**Comment by o2sh** [comment]
Hi @arf20, I've just added the `.deb` package to the artifacts of the latest release https://github.com/o2sh/onefetch/releases/tag/2.18.1 

This the first time I do it so don't hesitate to report back if doesn't work as intended, I tested it using `sudo dpkg -i onefetch_2.18.1_amd64.deb`

**Comment by hlidotbe** [comment]
Hi @o2sh, I've tried to install onefetch 2.18.1 on Ubuntu 20.04 Focal through the PPA but I get the following error:

```
The following packages have unmet dependencies:
 onefetch : Depends: libc6 (>= 2.34) but 2.31-0ubuntu9.9 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I've checked and it's indeed the correct glibc version for this release so I'm not too sure how to proceed.

Same with the package in the GH release.

**Comment by arf20** [comment]
Sorry @o2sh I forgot to report back.
Your Debian package works in Debian 12.
I prefer `apt install ./<file>`
And the package details look correct

**Comment by o2sh** [comment]
Nice to hear @arf20, this issue can be closed then.

@hlidotbe, you seem to be running an old version of libc, you can maybe do  `sudo apt update && sudo apt upgrade` then try again. A second option would be to upgrade your ubuntu distribution to a newer version.

**Comment by spenserblack** [comment]
Not that this resolves the issue with installing via `apt`, but I also am on 20.04 on one of my workstations, and I can install it with `cargo install onefetch`. So perhaps this can be a workaround for you?
