### ISSUE TITLE
build for `aarch64-pc-windows-gnullvm` is broken

### ISSUE THREAD

**Issue by ognevnydemon** [o2sh/onefetch#1143]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

build fails with
```
= note: aarch64-w64-mingw32-clang: warning: argument unused during compilation: '-nolibc' [-Wunused-command-line-argument]
aarch64-w64-mingw32-clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
lld: error: unable to find library -lwindows.0.48.0
lld: error: unable to find library -lwindows.0.48.0
aarch64-w64-mingw32-clang: error: linker command failed with exit code 1 (use -v to see invocation)
 
error: could not compile `onefetch` (bin "onefetch") due to previous error
```

### Expected behavior 🤔

successful build 

### Steps to reproduce 🕹

1. download msys2
2. take PKGBUILD recipe for onefetch
3. run `makepkg-mingw -s` in CLANGARM64 environment

### Possible Solution 💡

resolved in https://github.com/msys2/MINGW-packages/pull/18182

**Comment by jeremyd2019** [comment]
Hopefully just a matter of updating windows-targets to 0.48.1.

**Comment by jeremyd2019** [comment]
Yes, that works: https://github.com/msys2/MINGW-packages/commit/0b466003087e84767cdb9a20463ced70e287a966

**Comment by spenserblack** [comment]
@jeremyd2019 Thanks for investigating!
