### ISSUE TITLE
cargo test after cargo build, or cargo build --release

### ISSUE THREAD

**Issue by Kloenk** [o2sh/onefetch#117]
Looking forward to merging your PR 👍 ! Just one quick question:
Why move `cargo build` below `cargo test`? Tests require a successful build. If the project has not been built, `cargo test` will build it, so building *after* tests have run successfully is a bit redundant.

_Originally posted by @spenserblack in https://github.com/o2sh/onefetch/pull/110_

This is still unresolved, as we did not decide if we should move ```cargo test``` arround, or make the build a release build, becaus of maybe some different output in dependencies.

**Comment by spenserblack** [comment]
Thanks, completely missed that!
@o2sh, do you have a preference to the order that Travis-CI does these tasks?

**Comment by Kloenk** [comment]
I still believe that we should do a release build for testing.
