### ISSUE TITLE
Screenshot in Readme shows wrong license

### ISSUE THREAD

**Issue by floitsch** [o2sh/onefetch#118]
I didn't try the script, but the screenshot of the dart sdk repository [0] states that the sdk is GPLv3. The actual license of the dart sdk is BSD:
https://github.com/dart-lang/sdk/blob/master/LICENSE

[0] https://raw.githubusercontent.com/o2sh/onefetch/master/assets/kitty.png

**Comment by spenserblack** [comment]
I just cloned down dart-lang/sdk, ran onefetch (as of d66e76f875eae6c7981d4f6626d321d8dd064dda) on it, and got an unknown license (`??` in the License field). Which is a bit better than displaying the wrong license.
🤔 @CephalonRho, did you happen to change the license in your local repository for a better-looking screenshot?

**Comment by spenserblack** [comment]
Just checked out the documentation for `license`. 0.7.1 (the version we're using) doesn't seem to support BSD licenses, but 0.8.0 will.

**Comment by CephalonRho** [comment]
I didn't make that screenshot, and my local copy of the dart sdk is unmodified. Running onefetch on the revision in the screenshot shows an unknown license for me too.
![image](https://user-images.githubusercontent.com/28684831/67642874-92d90580-f910-11e9-86cd-ba6c1b04fa93.png)

Seems like either @o2sh is using a modified version of the dart sdk or `license` is behaving weirdly because it doesn't support BSD licenses.

**Comment by o2sh** [comment]
> Seems like either @o2sh is using a modified version of the dart sdk

Bingo :sweat_smile: 

> Just checked out the documentation for license. 0.7.1 (the version we're using) doesn't seem to support BSD licenses, but 0.8.0 will.

Let's upgrade then :+1:

**Comment by spenserblack** [comment]
Looks like I was mistaken. There's only partial BSD licence support. Even though there are [several BSD license structs](https://docs.rs/license/0.8.0/license/index.html#structs), A [glance over the source code](https://docs.rs/license/0.8.0/src/license/lib.rs.html#436-497) makes me think there's no support yet for determining what license is in use.

**Comment by o2sh** [comment]
#119
