### ISSUE TITLE
Switch from `actions-rs/*` actions

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#1188]
Looks like the whole `actions-rs` organization is archived, so we can't expect any more updates. `actions-rs/install` uses the deprecated `node12` runner and is forced to run on `node16` instead. This seems fine for now, but might become a problem as the minimum Node version for GitHub Actions continues to be increased.

**Comment by o2sh** [comment]
Thanks for the heads up @spenserblack
I created a PR to address this issue #1191
