### ISSUE TITLE
Upgrade [license] dependency 0.7.1 --> 0.8.0

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#119]
The [License](https://github.com/evenorog/license) API seems to have changed. After upgrading, I'm getting the following errors/warnings:

![DeepinScreenshot_select-area_20191027235053](https://user-images.githubusercontent.com/13710835/67643169-a4bca780-f914-11e9-81b7-0468e287b463.png)

**Comment by portgasd666** [comment]
@o2sh  I will work on this
