### ISSUE TITLE
[doc] Universal install anchor is broken

### ISSUE THREAD

**Issue by kinow** [o2sh/onefetch#1194]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

You go to https://github.com/o2sh/onefetch/wiki/installation and click on the universal installation. Nothing happens.

### Expected behavior 🤔

It takes you to the universal installation page.

### Steps to reproduce 🕹

1. Go to https://github.com/o2sh/onefetch/wiki/installation
2. Click on universal installation

### Additional context/Screenshots 🔦

NA

### Possible Solution 💡

Fix the link in the Wiki, or change the text, or keep it and adjust the Markdown link, etc. Thanks

**Comment by o2sh** [comment]
Should be fixed, thanks for reporting this @kinow

**Comment by kinow** [comment]
Indeed it is! Thanks for the quick fix. Closing :+1:
