### ISSUE TITLE
Thread 'main' panicked 

### ISSUE THREAD

**Issue by Symbian9** [o2sh/onefetch#120]
**OS:** Debian 9.x (x86_64)

**Version:** `1.6.5` (official binary) - https://github.com/o2sh/onefetch/releases/download/v1.6.5/onefetch_linux_x86-64.zip

```
$ RUST_BACKTRACE=full ./onefetch -d /path/to/my/git/repo/
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x556569aae31b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x556569aae31b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x556569aae31b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x556569aae31b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x556569aae31b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x556569aadff6 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x556569aaea8d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x556569aae612 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x556569aae4f6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x556569ace77d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x556569ace6bc - core::panicking::panic::hda536e6f3accfb91
                               at src/libcore/panicking.rs:49
  11:     0x5565698e80e4 - onefetch::main::he6f9671556045fc2
  12:     0x5565698c8b06 - std::rt::lang_start::{{closure}}::h1844d7221d4a8650
  13:     0x556569aae493 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  14:     0x556569aae493 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  15:     0x556569ab62ea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  16:     0x556569aaf05d - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  17:     0x556569aaf05d - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  18:     0x556569aaf05d - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  19:     0x5565698e9012 - main
  20:     0x7fe3dec262e1 - __libc_start_main
  21:     0x5565698c15da - _start
  22:                0x0 - <unknown>
```

**Comment by jyn514** [comment]
Problem is here, it shouldn't be calling unwrap on user input. The quick and dirty way to fix this is `expect`.

https://github.com/o2sh/onefetch/blob/master/src/main.rs#L192

**Comment by spenserblack** [comment]
I think this has been fixed by 91b554c918e485bf4ad56ea75794fa0fb64717af. The issue was that one of the functions for getting repo data was not using the directory passed by the user. It would always look into the current directory, causing inaccurate info when run in a different repo than the directory passed, and the error you just experience when run from a directory that is not a repo.

**Comment by spenserblack** [comment]
@jyn514, that unwrap is actually OK, and should never cause a panic. Onefetch's `clap::App` configuration guarantees that `"directory"` will always have a value, as it has a default value. See [this line](https://github.com/o2sh/onefetch/blob/master/src/main.rs#L104).

**Comment by aditsachde** [comment]
Sorry I can't help, but I'm also having the same issue, with the exact same stack trace, using the binary and a similar command. Are there any workarounds?

**Comment by o2sh** [comment]
> any workarounds

Build from HEAD with `cargo run`

----
@aditsachde @Symbian9 we're gonna push a new release by the end of the week. Hopefully, this will resolve your issue.

**Comment by Symbian9** [comment]
> we're gonna push a new release by the end of the week. Hopefully, this will resolve your issue.

OK.

Please, do not close this issue until new release binary would be available.

**Comment by o2sh** [comment]
@Symbian9 a new binary is available

**Comment by Symbian9** [comment]
> a new binary is available

Not work on Debian 9 stretch:

```
$ ./onefetch -d /path/to/my/git/repo/
./onefetch: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./onefetch)
```

Please, decrease dependency!

**Comment by jyn514** [comment]
That's a separate issue, and probably can't be fixed while keeping a dynamically linked libc

**Comment by Symbian9** [comment]
FTR, on Debian 9 there is `GLIBC_2.24`, so just re-build binary with lower version dependency.

As I know, latest *Blender* 2.8x binary built with `GLIBC_2.17`.

**Comment by Symbian9** [comment]
FTR, on Debian 9 there is `GLIBC_2.24`, so just re-build binary with lower version dependency.

As I know, latest *Blender* 2.8x binary built with `GLIBC_2.17`.
