### ISSUE TITLE
Size: 0 bytes (90 files)

### ISSUE THREAD

**Issue by pawamoy** [o2sh/onefetch#122]
Well... it's in the title :smile: 

Running it on a local clone of https://github.com/pawamoy/aria2p.

**Comment by spenserblack** [comment]
Size is calculated by the first line returned from the command `git -C <your-repo> count-objects -vH` Could you show us the output of this command? (`-C <your-repo>` can be omitted if you're running git in the repo in question). Thanks!

**Comment by pawamoy** [comment]
Sure!

```console
$ git count-objects -vH 
count: 1988
size: 9.39 MiB
in-pack: 0
packs: 0
size-pack: 0 bytes
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

**Comment by spenserblack** [comment]
>It seems `onefetch` is picking the `size-pack` value.

Yes, that's correct. Sorry, I was wrong earlier in saying it was the "first line". Was thinking of a different info field 🤦‍♂ 
Could you run this command in your local repo?
```bash
$ find .git/objects -type f
```

**Comment by pawamoy** [comment]
No problem :slightly_smiling_face: 

The command `find .git/objects -type f` outputs 1995, I don't think you want them all, so here are the first 10:

```
.git/objects/6b/89fcce946b4fd5b63b023207ef7961ddf6e1e6
.git/objects/6b/239a70185d47108034b76f68b2e5bb490b90e4
.git/objects/6b/0a477d3794a6f90754ab7c020b4e697360f53b
.git/objects/6b/30fabfc6cd4c573c1fa41b6d33c5c53a6c1e15
.git/objects/6b/753a40d77a91aa25fd4bb518593bceb7011a46
.git/objects/28/216055080981e6c78eb908769f2e08cea2b9c9
.git/objects/28/3e8af7371cdd1c7492d06699cded2aa5824906
.git/objects/db/c62711c906028e1e3fe6a0218906c7afa91aec
.git/objects/db/81b06182ac75f30a3cd6c6620ca1664b9ba882
.git/objects/db/c705553706229ac4888a5623a8b22e186d7992
```

**Comment by spenserblack** [comment]
Try either of these commands.
```bash
$ find .git/objects -type f | grep pack
$ ls -lh .git/objects/pack/
```
What I'm thinking is that there aren't any pack files in your local repo for some reason. I'll need to read up on git's behavior some more to figure out why that would happen.

**Comment by pawamoy** [comment]
Indeed, first command outputs nothing, second command says `total 0`.

Running `git gc --prune=now` in another repo where `onefetch` reported a size of `0` seems to have fixed the issue. From that [stackoverflow thread](https://stackoverflow.com/questions/30999879/git-garbage-size-out-of-control-need-understanding), `git gc` also "repacks" the repository, so it makes sense (though I don't understand what I'm doing :smile:)

**Comment by pawamoy** [comment]
I think we can close this issue since it's not `onefetch`'s responsibility to run git commands in local repositories :smile: 

Reopen if needed!
