### ISSUE TITLE
ISC license not recognized

### ISSUE THREAD

**Issue by pawamoy** [o2sh/onefetch#123]
It seems that the ISC license is not recognized. I saw comments about upgrading the `license` dependency, maybe that would fix it.

**Comment by o2sh** [comment]
https://docs.rs/license/0.8.0/license/

![image](https://user-images.githubusercontent.com/13710835/67663940-e118f380-f966-11e9-8dce-226d6aa455d7.png)

#119 will resolve it, hopefully

**Comment by o2sh** [comment]
@pawamoy Can you compile from HEAD and try again ?

**Comment by pawamoy** [comment]
Just tried it, it still does not recognize the ISC license. However I'm not using the EXACT text of the license, as I'm adding `ISC License` then `Copyright (c) year1-year2, FirstName Name` at the top. GitHub and GitLab successfully recognize it though.

**Comment by o2sh** [comment]
@ebroto Now, when I run onefetch on [aria2p](https://github.com/pawamoy/aria2p), I get:

![image](https://user-images.githubusercontent.com/13710835/68253659-c7dc0b00-0028-11ea-8381-2d2001ce8a64.png)

which is incorrect as the License should be ISC.

However, when I run askalono by itself --> 

![image](https://user-images.githubusercontent.com/13710835/68253747-0376d500-0029-11ea-8e65-9ceebfc8e92b.png)

Any idea why?
