### ISSUE TITLE
Installer hash does not match

### ISSUE THREAD

**Issue by laurentkempe** [o2sh/onefetch#1296]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Runing winget upgrade o2sh.onefetch we get following error "Installer hash does not match."

```powershell
winget upgrade o2sh.onefetch
Found onefetch [o2sh.onefetch] Version 2.20.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
Downloading https://github.com/o2sh/onefetch/releases/download/2.20.0/onefetch-setup.exe
  ██████████████████████████████  5.82 MB / 5.82 MB
Installer hash does not match.
```

### Expected behavior 🤔

Runing winget upgrade o2sh.onefetch should update it

### Steps to reproduce 🕹

1. winget upgrade o2sh.onefetch
2. Check output

**Comment by spenserblack** [comment]
Just checked and confirmed they don't match. @vedantmgoyal9 @russellbanks Any ideas?

**Comment by spenserblack** [comment]
:thinking: I'm curious why it ever mismatched to begin with. The installer hash was written by our release workflow, right?

**Comment by laurentkempe** [comment]
👍🏼 Works like a charm @o2sh Thanks for the lightning-fast fix 👏🏼

**Comment by o2sh** [comment]
> 🤔 I'm curious why it ever mismatched to begin with. The installer hash was written by our release workflow, right?

That's right.

Beside, I don't understand how the initial PR - created by the CD - passed https://github.com/microsoft/winget-pkgs/pull/144949, the hash mismatch should have been caught here 🤔

**Comment by spenserblack** [comment]
Perhaps during CD we should also upload the executable as a workflow artificact, just so we can reference the artifact as the "real" file from the workflow. It would be a bit reassuring to compare the hashes between the artifact and the release asset in the future.
