### ISSUE TITLE
Any binary for macOS?

### ISSUE THREAD

**Issue by orklann** [o2sh/onefetch#130]
I can not find any binary for macOS, but I am lazy to build it myself, 
can you build one for macOS?

**Comment by butuzov** [comment]
brew formula was release yesterday.

**Comment by orklann** [comment]
> brew formula was released yesterday.

How can I install with homebrew?

```
brew install onefetch                       
Updating Homebrew...
Error: No available formula with the name "onefetch"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by butuzov** [comment]
did you
```bash
brew update
```

**Comment by orklann** [comment]
I works now by running `brew update` and install it with brew. Thank you for the help.

**Comment by butuzov** [comment]
yw. close the issue =)

**Comment by o2sh** [comment]
Thanks for the help @butuzov 
I wasn't even aware a onefetch was pushed to Homebrew...

Unfortunately, this version is a little updated.

----
@erikgaal  Thanks a lot for submitting onefetch to HomeBrew, could you maybe submit 1.7.0?
I don't have MacOs, unfortunately...

**Comment by erikgaal** [comment]
Sure, @o2sh!

**Comment by erikgaal** [comment]
https://github.com/Homebrew/homebrew-core/pull/45975

**Comment by joseluisq** [comment]
I have tested via `brew` today and it works!

```sh
brew install onefetch
```
I think the update could come with some README updates specifying its use.

**Comment by joseluisq** [comment]
Sorry doc it's aready there https://github.com/o2sh/onefetch/wiki/Installation#macos-homebrew

Issue can be closed.
