### ISSUE TITLE
Onefetch counts Merge Commits

### ISSUE THREAD

**Issue by igroeg** [o2sh/onefetch#131]
Think that it's not ok to count merge commits since they are with no value at all and it makes wrong statistics.

**Comment by spenserblack** [comment]
Should be simple; there's a `--no-merges` flag for `git rev-list`.
But do merge commits really have no value? Some of them can have changed, or even new code.

**Comment by o2sh** [comment]
I think we should keep the default behaviour as it is and add a flag that would enable `--no-merges` on `get_commits` and `get_authors`
