### ISSUE TITLE
Lua dark blue color make it hard to read

### ISSUE THREAD

**Issue by olivertzeng** [o2sh/onefetch#1336]
### Summary 💡

The text should not show in such a dark color especially in dark backgrounds 
![image](https://github.com/o2sh/onefetch/assets/86348833/73014d6a-f883-4221-a6d1-e59e75a23b26)

### Motivation 🔦

It makes the panel hard to read

**Comment by o2sh** [comment]
Purple on black is indeed pretty bad😅  here is a suggestion with a lighter blue:

before:

![image](https://github.com/o2sh/onefetch/assets/13710835/82d49269-1bcf-4a91-af0f-437c77791188)

after:

![image](https://github.com/o2sh/onefetch/assets/13710835/ca45df14-810e-4b74-a4bb-8f717549200f)

**Comment by olivertzeng** [comment]
> Purple on black is indeed pretty bad😅  here is a suggestion with a lighter blue:
> 
> 
> 
> before:
> 
> 
> 
> ![image](https://github.com/o2sh/onefetch/assets/13710835/82d49269-1bcf-4a91-af0f-437c77791188)
> 
> 
> 
> after:
> 
> 
> 
> ![image](https://github.com/o2sh/onefetch/assets/13710835/ca45df14-810e-4b74-a4bb-8f717549200f)
> 
> 
> 
> 

That looks 1000 times better
