### ISSUE TITLE
Wiki page "Images in the terminal" refers to incorrect command line argument

### ISSUE THREAD

**Issue by df-salaz** [o2sh/onefetch#1341]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

The wiki says that `--image-backend` can be used to set the image protocol.

### Expected behavior 🤔

`--image-protocol`  should be used instead.

**Comment by o2sh** [comment]
Good catch @df-salaz 👍 

Should be fixed with [df49072](https://github.com/o2sh/onefetch/commit/df49072e277de889568fa5ce61275d0704950a75)
