### ISSUE TITLE
1.7.0 release tagged incorrectly

### ISSUE THREAD

**Issue by erikgaal** [o2sh/onefetch#135]
Hi there,

It seems that the 1.7 release was tagged incorrectly as `1.7.0` instead of `v1.7.0` as per convention. The `v` is missing before the version number. When this is tagged I can update the Formula on Homebrew too.

**Comment by o2sh** [comment]
Yes, that was voluntary. I tried following [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

Does it has to be tagged v1.7.0?

**Comment by erikgaal** [comment]
It doesn't _need_ to be tagged as `v1.7.0` for Homebrew, but the _general_ convention is to prefix version with `v`.

**Comment by o2sh** [comment]
done

**Comment by erikgaal** [comment]
Thanks!
