### ISSUE TITLE
debian package was not released for 2.22.0 

### ISSUE THREAD

**Issue by Vitexus** [o2sh/onefetch#1422]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Please add the deb package to assets in [2.22.0](https://github.com/o2sh/onefetch/releases/tag/2.22.0)

![image](https://github.com/user-attachments/assets/5a9bcb78-ae45-48dd-9301-611af6ddccf9)

### Expected behavior 🤔

package onefetch_2.22.0_amd64.deb is downloadable

**Comment by o2sh** [comment]
Sorry for the delay, @Vitexus.
The 2.22.0 .deb package is now available on the https://github.com/o2sh/onefetch/releases/tag/2.22.0

**Comment by Vitexus** [comment]
Happy :)
