### ISSUE TITLE
Add C3 language

### ISSUE THREAD

**Issue by LainLayer** [o2sh/onefetch#1434]
### Summary 💡

Website of the language: https://c3-lang.org/
currently it is recognized as C++ incorrectly

**Comment by spenserblack** [comment]
What file extensions are associated with C3? Anything besides `.c3`?

**Comment by LainLayer** [comment]
theres `.c3l` which is a binary format, and `.c3i` which is textual

**Comment by LainLayer** [comment]
Sure
