### ISSUE TITLE
[License Detection] Switch to askalono

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#147]
Onefeth currently relies on [license](https://github.com/evenorog/license/blob/master/src/lib.rs), for license detection.

After looking at the code, it seems only capable of detecting -->
```
pub fn from_id_ext(id: &str) -> Option<&'static dyn LicenseExt> {
    match id {
        "AGPL-3.0-only" => Some(&AGPL_3_0_only),
        "Apache-2.0" => Some(&Apache_2_0),
        "CC0-1.0" => Some(&CC0_1_0),
        "GPL-3.0-only" => Some(&GPL_3_0_only),
        "LGPL-3.0-only" => Some(&LGPL_3_0_only),
        "MIT" => Some(&MIT),
        "MPL-2.0" => Some(&MPL_2_0),
        "Unlicense" => Some(&Unlicense),
        _ => None,
    }
}
```

Which is clearly unsufficient...hence #133 #118 and #123 

[Askalono](https://github.com/amzn/askalono) seems to be the right candidate for the job,.

Let's migrate 💯

**Comment by ebroto** [comment]
I would like to work on this one
