### ISSUE TITLE
Please add support for Markdown

### ISSUE THREAD

**Issue by KathyReid** [o2sh/onefetch#148]
Firstly, the project is amazing!
Thank you for all your efforts. 

I do a lot of documentation and writing work in Markdown, is it possible to support Markdown? 
If you point me to documentation on how to add support, I'm very happy to have a go at a PR. 

Markdown is [supported by Tokei](https://github.com/XAMPPRocky/tokei#supported-languages)

_The reason I think Markdown is not supported yet is that I ran it on a repo that is primarily Markdown, and it stated:_

```
kathyreid@kathyreid-ubuntu-X510UQ:~/Dropbox/ANU/CECS8001-Lab/kathy-sensebook-semester2$ onefetch -d .
Error: Could not find any source code in this directory
```

Kind regards, and thanks again for your efforts.

**Comment by o2sh** [comment]
![DeepinScreenshot_select-area_20191102223827](https://user-images.githubusercontent.com/13710835/68077294-8c8bd300-fdc1-11e9-8470-f69b7209b7c3.png)
