### ISSUE TITLE
Option to disable the colored squares at the bottom

### ISSUE THREAD

**Issue by acarl005** [o2sh/onefetch#153]
Hi @o2sh, I love this program! I like how I can customize the output, except I cannot remove the colored squares at the bottom.

<img width="1093" alt="Screen Shot 2019-11-07 at 4 49 42 PM" src="https://user-images.githubusercontent.com/8334252/68430830-d63c3b00-017e-11ea-8c4a-b07a8898d3b7.png">
It doesn't have any relevance to the git repo. A command line option to remove it would be awesome.

**Comment by o2sh** [comment]
All right, I'll add a command flag to hide the color blocks 👍

**Comment by o2sh** [comment]
![image](https://user-images.githubusercontent.com/13710835/68528023-1b32af80-02ee-11ea-8776-b1eb8e904436.png)

**Comment by o2sh** [comment]
Hi @acarl005, Is this what you wanted?

Can we close this issue?

Thanks :+1:
