### ISSUE TITLE
Wrong license detected

### ISSUE THREAD

**Issue by Phundrak** [o2sh/onefetch#156]
**Wrong license detected**
When testing onefetch against [this project](https://labs.phundrak.com/phundrak/langue-phundrak-com) ([github mirror](https://github.com/phundrak/langue-phundrak-fr)), I noticed onefetch detected the MPL-2.0 license, despite the absence of said license. The two licenses for this project are the AGPL-3.0 and BY-NC-SA, the former being in its own file [agpl-3.0.md](https://github.com/Phundrak/langue-phundrak-fr/blob/master/agpl-3.0.md) and the latter is mentionned in the [LICENSE.org](https://github.com/Phundrak/langue-phundrak-fr/blob/master/LICENSE.org) (although parsing such file would surely be tricky).

**To Reproduce**
1. Clone the project
2. Run onefetch against the project
3. See the detected license

**Expected behavior**
When a LICENSE.org or LICENSE.md or LICENSE file cannot be clearly identified, onefetch should either try to detect license files or not display any license at all instead of giving wrong information.

**Screenshots**
[Link to screenshot](https://cdn.phundrak.com/img/onefetch-license-issue.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux (Arch Linux)
 - Rust version: 1.40 nightly
 - Version: 2.0.1 (latest master commit at the time)

**Additional context**
The version error that can be seen in the screenshot should be normal behavior, since the test project does not have any version.

**Comment by ebroto** [comment]
Hi, thanks for reporting the issue! We were indeed using an invalid minimum confidence threshold for the license detection engine. It should now report an unknown license for the linked repo.

I would prefer to stick to the most followed convention and look for files matching `LICENSE*` and `COPYING*`, otherwise I feel that trying to find licenses in other files could be slow and less reliable.

**Comment by Phundrak** [comment]
I can confirm the issue has been resolved, the license is now displayed as unknown. Thank you!
