### ISSUE TITLE
Publish v2.1.0 to HomeBrew + MacOS binary

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#159]
Hi @erikgaal,

Would you be so kind as to publish v2.1.0 to Homebrew and maybe attach the binary for MacOS to the latest release?

**Comment by erikgaal** [comment]
https://github.com/Homebrew/homebrew-core/pull/46590

**Comment by erikgaal** [comment]
Hi @o2sh,

I'm looking into setting up a script using GitHub Actions that automatically published new version to Homebrew. But we (you) need to request access for it [here](https://github.com/features/actions/signup/?account=o2sh). Would you like to do that?

Thanks!

**Comment by o2sh** [comment]
Done :+1:

**Comment by erikgaal** [comment]
2.1.0 is now available on Homebrew
