### ISSUE TITLE
Support for Groovy

### ISSUE THREAD

**Issue by AKolakowska47** [o2sh/onefetch#163]
I would be awesome if you can add support for Groovy :)

**Comment by o2sh** [comment]
![DeepinScreenshot_select-area_20191115001752](https://user-images.githubusercontent.com/13710835/68904126-6f4df180-073d-11ea-83ef-8e892084e4a8.png)

**Comment by o2sh** [comment]
@AKolakowska47 are you okay with this?

If so, can you plz close this issue.

Thanks

**Comment by AKolakowska47** [comment]
@o2sh Your commit seems to be OK, but  I'm waitin' for binary to check it ;) 
When the new one (2.1.1.)  will be available?

**Comment by spenserblack** [comment]
@AKolakowska47 [This binary](https://github.com/o2sh/onefetch/files/3859156/onefetch.tar.gz) was built from 90bdc4ecb48d71e23871e4266a96e5d381c7d226

**Comment by o2sh** [comment]
[Onefetch 2.2.0 ](https://github.com/o2sh/onefetch/releases/tag/v2.2.0) is now available.
