### ISSUE TITLE
Bold makes all colors bright

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#164]
It *looks like* `onefetch -c 0 8` uses BrightBlack for both colors, even though it actually doesn't.
`onefetch -b -c 0 8` properly looks like it uses Black for primary color and BrightBlack for secondary color.
This appears to be a limitation with ANSI, since `echo -e "\e[0;30;1mBlack\e[0m"` and `echo -e "\e[0;90;1mBrightBlack\e[0m"` both look the same in xterm.
Perhaps the bold flag should default to off instead of on? Or at least some warning in the help message for `-c` regarding this. Not sure the best way to fix this would be, but users are being limited to half of the available color options.

**Comment by o2sh** [comment]
I fail to see any clever way to approach this, It's important to have a consistent behavior across terminals. So maybe, we should consider using only 8 colors instead of 16; I think we should keep the bold format as default.
---
BTW, Thanks for pointing that out @spenserblack :+1:

**Comment by spenserblack** [comment]
Yeah, I think that may be the best way. The only other way I could think of would be giving the user the option to select 16-color mode, which would automatically disable bold. But that might be behavior users would find confusing.
Tested this in Powershell too, recently, same behavior seems to apply.

So I guess the best way would be to remove half the color options and color blocks :crying_cat_face:
