### ISSUE TITLE
Cargo install

### ISSUE THREAD

**Issue by alichtman** [o2sh/onefetch#17]
It would be awesome if this could be installed with a package manager.

**Comment by o2sh** [comment]
I agree.
For starters, I'll try and submit it to the Arch User Repository.

**Comment by o2sh** [comment]
But then only people with rust can use it.

Still, your point is valid, I'll start with cargo.

**Comment by kiedtl** [comment]
What about Windows installation? (with [scoop](https://scoop.sh))

**Comment by alichtman** [comment]
You can use `cargo` on Windows.

**Comment by o2sh** [comment]
The binary for windows is attached to the [release](https://github.com/o2sh/onefetch/releases/tag/v1.5.4)

Thx for the suggestion @kiedtl
