### ISSUE TITLE
Suggestion: Ignore /doc* when determining primary language.

### ISSUE THREAD

**Issue by philer** [o2sh/onefetch#171]
Case in point, I use automatically generated documentation which is a whole bunch of html files, so onefetch thinks my project is about html. I know I can specify a language via the -a switch but it still seems like a fairly easy change to avoid this. It is very common to include documentation in /doc or /docs or /documentation, so I suggest ignoring these directories when determining the project's language.

**Comment by o2sh** [comment]
Hi @philer 
You can add a `.tokeignore` file at the root of your repo with all the folders you want onefetch to ignore.
