### ISSUE TITLE
Failed to recognize Emacs Lisp repo

### ISSUE THREAD

**Issue by cireu** [o2sh/onefetch#172]
Reproduce step

```sh
git clone https://github.com/emacs-elsa/Elsa
cd Elsa
ls *.el
onefetch
```

Show repo as Markdown repo but expect Elisp repo.

**Comment by o2sh** [comment]
Hi @cireu,
I've just pushed a new [release](https://github.com/o2sh/onefetch/releases/tag/v2.2.0) which added support for Elisp.

Plz try again :+1:

**Comment by cireu** [comment]
Nice job! :+1:
