### ISSUE TITLE
Language: Racket?

### ISSUE THREAD

**Issue by emacsomancer** [o2sh/onefetch#174]
For a repo with a mix of .org and .rkt files, it only seems to 'see' .org. E.g.: https://gitlab.com/dustyweb/terminal-phase

**Comment by o2sh** [comment]
Thanks for pointing that out @emacsomancer 
It should work fine now.

![2020-04-29_21-08](https://user-images.githubusercontent.com/13710835/80636390-aac74880-8a5d-11ea-9f8c-b98d5c3eecd8.png)
