### ISSUE TITLE
Problem with dependencies for 2.3.0 release

### ISSUE THREAD

**Issue by jubalh** [o2sh/onefetch#183]
When I try `cargo vendor` to create a vendor package containing all the dependencies I get the following:

```
 Downloading ahash v0.3.8
error: failed to sync

Caused by:
  failed to fetch package

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.8/Cargo.toml`

Caused by:
  invalid type: string "fat", expected a boolean for key `profile.bench.lto`
```

Seems like something wrong with ahash? Does getting ahash work for you?

**Comment by o2sh** [comment]
Hi @jubalh 
Just tried it on another machine without any issue.

Maybe try upgrading your rustc version to latest stable? Run `rustup update stable`

**Comment by jubalh** [comment]
@o2sh you are right! With a newer version it works without problems. Sorry about the noise! Thanks for the help!
openSUSE package is updated :)

**Comment by o2sh** [comment]
No problem, thanks a lot for maintaining the openSUSE package @jubalh
