### ISSUE TITLE
Use git2 libray instead of git log command in get_authors() and get_creation_time

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#197]
Following a Suggestion by @spenserblack  in #181

------

I wonder if interaction with repo history via the References iterator would be faster than running git log commands. For example, assuming References are sorted chronologically,

```
let repo: Repository; // declare repo
let first_commit = repo.rev().next().unwrap().peel_to_commit().unwrap();
```

Using a Rust iterator, which lazily evaluates its items, might be faster than executing git commands.

**Comment by o2sh** [comment]
get_creation_time() using git2 instead of git log:

```
    async fn get_creation_time(repo: &Repository) -> Result<String> {
        let mut revwalk = repo.revwalk().unwrap();
        revwalk.push_head().unwrap();
        revwalk.set_sorting(git2::Sort::TIME | git2::Sort::REVERSE).unwrap();
        let first_commit_rev = revwalk.next().unwrap();
        let first_commit = repo.find_commit(first_commit_rev.unwrap()).unwrap();
        let ts = time::Timespec::new(first_commit.time().seconds() + (first_commit.time().offset_minutes() as i64) * 60, 0);
        let time = time::at(ts);
        Ok(format!("{}",time.strftime("%a %b %e %Y").unwrap()))
    }
```
On the same Linux repo, I am now getting : `get_creation_time --> 12.539735171s` compared to 9.860741358s with the old version.

Did I miss smth, or is this actually worse ?

**Comment by spenserblack** [comment]
:thinking: I guess executing git commands is faster after all.
We could probably use the result of `get_commits` to get creation time. Where n = number of commits, `git log -1 HEAD~{n}` should get the first commit. That may be faster than reversing then looking up.

**Comment by o2sh** [comment]
> We could probably use the result of get_commits to get creation time.

Great idea, let's do that.
