### ISSUE TITLE
Use git log once to derive get_commits/get_creation_time/get_authors 

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#198]
Following a Suggestion by @spenserblack in #197 

-------

Considering the significant impact on the response time of the `git log` command. It seems more reasonable to call it only once and use its output to derive:

- Number of Commits: get_commits()
- Creation Time: get_creation_time()
- Authors: get_authors()

**Comment by spenserblack** [comment]
`git log --pretty` could probably be used to get info in a way we can parse. The `.lines()` function returns a double-ended iterator, so you could call `.next_back()` to get stats of first commit, then iterate the rest normally.
