### ISSUE TITLE
Refactor language.rs

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#205]
Currently, adding support for a new language requires modifying the language.rs at multiple locations.
This process can be quite cumbersome and error prone (especially for new contributors).

Some shortcuts can be taken:

- Assuming the ascii file to be in "../resources/language.ascii" => match case in `get_ascii_art()` no more needed
- Using `tokei::LanguageType` instead of our own Enum, else (if not possible) assume that the name matches => match case in fn `from(language: tokei::LanguageType)` no more needed.
- ...

**Comment by spenserblack** [comment]
We could probably use a macro for most language definition (the [paste crate](https://crates.io/crates/paste) is good for this). This macro could also define tests.
