### ISSUE TITLE
Reduce size of Lua's ASCII logo

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#217]
Some of our ASCII logos exceed the max size imposed by our [Guideline](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#ascii-logo). As a striking example, Lua's ASCII logo is just enormous:

![lua](https://user-images.githubusercontent.com/13710835/94999189-176be380-05b8-11eb-9120-006c8da36fbb.png)

The idea would be to come up with a new ASCII logo for Lua with a width < MAX_WIDTH = 40 and height < MAX_HEIGHT = 25

-----

To check if your ASCII logo falls into the boundaries of width/height defined above, you can run `cargo test -- --ignored`

**Comment by maamim** [comment]
Hey, so I made a ASCII Lua logo but after running `cargo test -- --ignored` I found that there are some other logos too that aren't passing would you like me to take a look at them too?

**Comment by o2sh** [comment]
Hi @maash3r,
Sure! you can make multiple PRs, one per Logo you're resizing.

Looking forward to see your work.
