### ISSUE TITLE
Reduce size of Jupiter-Notebook's ASCII logo

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#219]
Some of our ASCII logos exceed the max size imposed by our [Guideline](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#ascii-logo). The Jupyter-notebook's ASCII logo is one of them:

![jnb](https://user-images.githubusercontent.com/13710835/95028898-38a9fe00-06a4-11eb-86af-9dc9d1433e6a.png)

The idea would be to come up with a new ASCII logo for Jupyter-notebook with a width < MAX_WIDTH = 40 and height < MAX_HEIGHT = 25

-----

To check if your ASCII logo falls into the boundaries of width/height defined above, you can run `cargo test -- --ignored`

**Comment by atluft** [comment]
I would like to resolve this one.

**Comment by maash3r** [comment]
@atluft have you already completed it? Just wanted to ask as I had come up with a solution too.

**Comment by aluft-logi** [comment]
no, go ahead and I will try another

**Comment by atluft** [comment]
@maash3r 
Go ahead, I will look at another one.

**Comment by maash3r** [comment]
@atluft Thanks.
@o2sh Can you assign it to me?
