### ISSUE TITLE
Reduce size of Objective-C's ASCII logo

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#222]
Some of our ASCII logos exceed the max size imposed by our [Guideline](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#ascii-logo). As a striking example, Objective-C's ASCII logo is just enormous:

![objective-c](https://user-images.githubusercontent.com/13710835/95029100-1dd88900-06a6-11eb-9f95-da26769f6784.png)

The idea would be to come up with a new ASCII logo for Objective-C with a width < MAX_WIDTH = 40 and height < MAX_HEIGHT = 25

-----

To check if your ASCII logo falls into the boundaries of width/height defined above, you can run `cargo test -- --ignored`

**Comment by atluft** [comment]
What do you think of this one?

![image](https://user-images.githubusercontent.com/2379260/95141971-8ecc7f00-0740-11eb-866f-d5cdb9cb00dd.png)
