### ISSUE TITLE
Reduce size of Php's ASCII logo

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#228]
Some of our ASCII logos exceed the max size imposed by our [Guideline](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#ascii-logo). The Php's ASCII logo is one of them:

![php](https://user-images.githubusercontent.com/13710835/95141520-bbe55580-0771-11eb-9ce3-6074826c57af.png)

The idea would be to come up with a new ASCII logo for Php with a width < MAX_WIDTH = 40 and height < MAX_HEIGHT = 25

-----

To check if your ASCII logo falls into the boundaries of width/height defined above, you can run `cargo test -- --ignored`

**Comment by rootEnginear** [comment]
I would like to work on this one. I am also working on some designs:
```
            @@@@@@@@@@@@@@@@
      @@@@@@@@@@|  |@@@@@@@@@@@@@@
   @@@@@@@@@@@@@|  |@@@@@@@@@@@@@@@@@
 @@@@@|        \|        \|        \@@@
@@@@@@|  |@@|  ||  |@@|  ||  |@@|  |@@@@
@@@@@@|  |@@|  ||  |@@|  ||  |@@|  |@@@@
 @@@@@|        /|  |@@|  ||        /@@@
   @@@|  |@@@@@@@@@@@@@@@@|  |@@@@@@@
      /  /@@@@@@@@@@@@@@@@/  /@@@@
            @@@@@@@@@@@@@@@@
```
```
            ################
      ##########|  |##############
   #############|  |#################
 #####|        \|        \|        \###
######|  |##|  ||  |##|  ||  |##|  |####
######|  |##|  ||  |##|  ||  |##|  |####
 #####|        /|  |##|  ||        /###
   ###|  |################|  |#######
      /  /################/  /####
            ################
```
```
            ****************
      **********|  |**************
   *************|  |*****************
 *****|        \|        \|        \***
******|  |**|  ||  |**|  ||  |**|  |****
******|  |**|  ||  |**|  ||  |**|  |****
 *****|        /|  |**|  ||        /***
   ***|  |****************|  |*******
      /  /****************/  /****
            ****************
```
What do you think?

**Comment by maash3r** [comment]
@rootEnginear 
Nice art, I like the second one the most. The one with `#`

**Comment by o2sh** [comment]
Great designs @rootEnginear 

> Nice art, I like the second one most.

I second that.

------

Don't hesitate to [add colors ](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#adding-support-for-a-new-language)to your logo :100:
