### ISSUE TITLE
New Rust ASCII Logo

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#234]
Rust deserves a better ASCII logo:

![rust](https://user-images.githubusercontent.com/13710835/95200393-9e9aa080-07de-11eb-9f2c-7fa3ac71bbaa.png)

We are looking for a cleaner design that falls between the limitations of max-width/max-height. More info  [here](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#adding-support-for-a-new-language).

-----

To check if your ASCII logo falls into the boundaries of width/height, you can run `cargo test -- --ignored`

**Comment by nguyenquannnn** [comment]
Hello, I would like to take a dig at this for Hacktoberfest. How close do we want to stay with the official logo?

**Comment by o2sh** [comment]
Hi, 
Well, given the constraints (size and colors), some compromises/creativity are usually necessary.

Looking forward to see your input.
