### ISSUE TITLE
Additional repository statistics

### ISSUE THREAD

**Issue by nazarimilad** [o2sh/onefetch#24]
What I think would be really nice to have are extra repository stats. 

For example if the project is from a Github repository, that Onefetch could show, thanks to the Github API, the following things:

* \# issues, 
* \# stars, 
* most important contributors, 
* latest release version

(Request from my tweet)

**Comment by o2sh** [comment]
Info added:
- Version
- Commits
I don't think I can do more without using the APIs which would make onefetch network dependant. Not sure this is best way to go...
