### ISSUE TITLE
Having too many languages will overflow text into the logo

### ISSUE THREAD

**Issue by aaronfranke** [o2sh/onefetch#25]
For example, this happens when I run onefetch on Godot:

![1](https://user-images.githubusercontent.com/1646875/52888970-f0933c00-314b-11e9-88f3-6ad85d949f1a.png)

**Comment by o2sh** [comment]
Thanks for pointing that out @aaronfranke, I added a break line character every time we  hit a multiple of 3

![deepinscreenshot_select-area_20190216225726](https://user-images.githubusercontent.com/13710835/52905722-7f808100-323e-11e9-95cd-485879aabeb1.png)

There was also an other bug that prevented onefetch from showing all the project's info (number of lines & License) --> also fixed (it only occured when the logo is smaller than the text).

I'll try pushing a new release tomorrow

**Comment by o2sh** [comment]
@aaronfranke can I close the issue ?
