### ISSUE TITLE
Reduce size of Nim's ASCII logo

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#250]
Some of our ASCII logos exceed the max size imposed by our [Guideline](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#ascii-logo). The Nim's ASCII logo is one of them:

![nim](https://user-images.githubusercontent.com/13710835/95599873-f260f000-0a51-11eb-8229-0ba35057fa25.png)

The idea would be to come up with a new ASCII logo for Nim with a width < MAX_WIDTH = 40 and height < MAX_HEIGHT = 25

-----

To check if your ASCII logo falls into the boundaries of width/height defined above, you can run `cargo test -- --ignored`

**Comment by tianlangwu** [comment]
Do you want a size down of this logo or a completely new logo for Nim's ASCII? I am not a creative person >.<. Can you assign this to me if you would like to just size down the logo :D.

**Comment by o2sh** [comment]
> Can you assign this to me if you would like to just size down the logo

Sure, go ahead :+1:

**Comment by tianlangwu** [comment]
Do you think this is ok? 
![logo](https://user-images.githubusercontent.com/60892464/95634128-2854a300-0a57-11eb-928a-cb7dbfc3b602.jpg)

It passed the test, but I am not sure you satisfied with it. 
![nim](https://user-images.githubusercontent.com/60892464/95634431-e546ff80-0a57-11eb-9127-8076b6ee0f65.jpg)

I also have some other version with little adjustments but I don't know which one is better. 
![nim2](https://user-images.githubusercontent.com/60892464/95634583-3ce56b00-0a58-11eb-906d-4b2cbea07fda.jpg)

![nim3](https://user-images.githubusercontent.com/60892464/95634587-3eaf2e80-0a58-11eb-94da-c6bb5500738e.jpg)
