### ISSUE TITLE
gracefully fallback for unknow source code

### ISSUE THREAD

**Issue by geeseven** [o2sh/onefetch#258]
Greetings,

I get an error when using `onefetch` on a AUR git repo:

```console
$ git clone https://aur.archlinux.org/onefetch.git
Cloning into 'onefetch'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 45 (delta 2), reused 45 (delta 2), pack-reused 0
Unpacking objects: 100% (45/45), 13.66 KiB | 1.14 MiB/s, done.

$ cd onefetch/

$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ ls -lah
total 24K
drwxr-xr-x  3 geeseven users 4.0K Oct 11 16:58 .
drwxr-xr-x 40 geeseven users 4.0K Oct 11 16:58 ..
drwxr-xr-x  8 geeseven users 4.0K Oct 11 17:12 .git
-rw-r--r--  1 geeseven users   34 Oct 11 16:58 .gitignore
-rw-r--r--  1 geeseven users  825 Oct 11 16:58 PKGBUILD
-rw-r--r--  1 geeseven users  439 Oct 11 16:58 .SRCINFO

$ onefetch
Error: Could not find any source code in this directory

$ onefetch --version
onefetch 2.4.0
```

My guess is it can't determine the language(s) and does not fall back to something generic. `¯\_(ツ)_/¯`

**Comment by yochananmarqos** [comment]
An AUR package repo contains no source code.

**Comment by geeseven** [comment]
Hey @yochananmarqos,

I fell that even if a repo does not contain 'source code', onefetch should fall back to use [unknown.ascii][0].   I'll change the topic for clarification. 

Also onefetch has support for non 'source code' repos like markdown and xml.  

[0]: https://github.com/o2sh/onefetch/blob/master/resources/unknown.ascii

**Comment by o2sh** [comment]
the Language::Unknown is actually useless (removed in [`9849aad`](https://github.com/o2sh/onefetch/commit/9849aad6b39f5a8d18797b5829c2d19e01994cc7)). If the language isn't supported by onefetch, no fallback is possible.
