### ISSUE TITLE
Specify path on the command line

### ISSUE THREAD

**Issue by HorlogeSkynet** [o2sh/onefetch#27]
Hey over here :wave:

Just wondering, do you think it would be possible to specify a path directly on the command line ?

```bash
onefetch /some/incredible/project/sources/
```

Sometimes we just want to output some info, without having to **move** into the effective target.

For your underneath git usages, the `-C` option could do the job !

Thanks, bye :bowing_man:

**Comment by o2sh** [comment]
:sweat_smile: I should have thought of that

It sould be good now, plz tell me if it's okay

Thanks a lot @HorlogeSkynet

**Comment by HorlogeSkynet** [comment]
Thanks to you @o2sh !

That's sincerely one of the quickest feature request that has been solved, and it works like a charm so here is a :100: for you.

(Sur la même idée, et aussi originellement inspiré de Neofetch / Screenfetch, qui pourrait t'intéresser : https://github.com/HorlogeSkynet/archey4)

:wave: Ossama
