### ISSUE TITLE
Support for more shell languages

### ISSUE THREAD

**Issue by Luke-zhang-04** [o2sh/onefetch#272]
Bash, ZSH, and other shells aren't detected

## Expected Behavior
`myFile.bash`, `myFile.zsh`, or maybe even `myFile.fish` are classified as `shell`

Files with `#!/bin/bash` or `#!/bin/zsh` are classified as `shell`

## Current behaviour
`myFile.sh` is classified as `shell`, but `myFile.bash` or `myFile.zsh` is ignored

Files with `#!/bin/sh` are classified as `shell`, but `#!/bin/bash` or `#!/bin/zsh` are ignored

**Comment by o2sh** [comment]
Indeed, Onefetch doesn't support Zsh nor Bash, only Shell.
#274 #273

**Comment by Luke-zhang-04** [comment]
Done in #276
