### ISSUE TITLE
Extend image backend support to ITerm2 Inline Images Protocol.

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#283]
As mentioned by @yoichi in #266, even though iterm2 seems to support SIXEL; it shows a broken output:

![image](https://user-images.githubusercontent.com/13710835/96747802-077e3d00-13c9-11eb-9148-44b2f98abbc0.png)

Apparently, iterm2 has its own [rendering protocol](https://iterm2.com/documentation-images.html) which _extends the xterm protocol with a set of proprietary escape sequences_. This xterm protocol must be the SIXEL protocol - Implemented by @CephalonRho - or smth close to it.

**Comment by mborejdo** [comment]
Looking forward to this. https://github.com/wez/wezterm is an awesome terminal-emulator with great Windows support. It also supports the iTerm2 inline image protocol and it would be great to have some windows love :-)

**Comment by o2sh** [comment]
From what I understood, @yoichi opened an [issue](https://gitlab.com/gnachman/iterm2/-/issues/9204) addressing this problem which was fixed int this [commit](https://gitlab.com/gnachman/iterm2/-/commit/119da0c28245d797dc124990676acfdd67789cfb)

Unfortunately, I don't have a machine running macOS so I can't test it.

**Comment by mborejdo** [comment]
Hey @o2sh. thanks for your reply. I am not sure I understand. Does this mean the iterm2 inline image support (which works also on windows on wezterm) will not be added, once the sixel-issue is resolved?

**Comment by o2sh** [comment]
@mborejdo, wezterm also supports Sixel

![wezterm](https://user-images.githubusercontent.com/13710835/97725766-d390cf00-1ace-11eb-8b09-9ff3a444fbe4.png)

However, this won't work on Windows.

**Comment by mborejdo** [comment]
hey @o2sh  . Yes, thats really unfortunate. Thats why I was hoping to have the iterm2-inline-image working on windows as this works as expected (almost)
Also unfortunately onefetch's --ascii does not help here, as the commandline is limited in length. Would it be possible to provide something like --ascii-file or the like so I could pass the base64 encoded inline-image to onefetch to be displayed instead of the default?

**Comment by o2sh** [comment]
> Also unfortunately onefetch's --ascii does not help here, as the commandline is limited in length.

Try this `onefetch —ascii-input "$(cat image_base64.txt)"`
