### ISSUE TITLE
Add Text Coloring via CLI flag

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#290]
By default, the info_lines' title (Project, HEAD, Pending, Version, etc) are colored based on the first color of the dominant language:
 
```rust
       let color = match self.colors().get(0) {
            Some(&c) => c,
            None => Color::White,
        };
```
It would be cool to let the user customize the text coloring via CLI flag, something like `onefetch --text-color X X X X`

This flag would work similarly to `--colors` except that it would only affect the text coloring.

The user would be able to provide up to 6 colors that would change the text colors in this order: title (red), ~ (green), underline (orange), title (maganta), colon (yellow), info (cyan)

![go_text_color](https://user-images.githubusercontent.com/13710835/96937022-86599f80-14c7-11eb-9e8c-c2e14a5a47ad.png)

**Comment by rogercyyu** [comment]
Hello, I'd like to take a shot at this. I'm guessing a lot of lines in `info.rs` are gonna be modified...

**Comment by o2sh** [comment]
Thanks @rogercyyu 

`I'm guessing a lot of lines in info.rs are gonna be modified...`

True 👍
