### ISSUE TITLE
Dependency Insights

### ISSUE THREAD

**Issue by Luke-zhang-04** [o2sh/onefetch#294]
Neofetch gives me a count of the number of packages I have installed. I was wondering if you would be willing to include a similar feature in Onefetch.

I'm willing to try and implement this, but I've never used Rust before, so I'm not sure how that'll go.

Also, this could impact performance, since the only way I can think of doing this would be to search for a certain package file (go.mod, requirements.txt, package.json, etc.) and then run a shell command (npm list, pip list, etc), which would not only be slow, but also open a shell session (probably has some security issues).

**Comment by o2sh** [comment]
> Neofetch gives me a count of the number of packages I have installed. I was wondering if you would be willing to include a similar feature in Onefetch.

I like this idea a lot :100: 

> I'm willing to try and implement this, but I've never used Rust before, so I'm not sure how that'll go.

We'll make sure to help you along the way :+1: 

> Also, this could impact performance, since the only way I can think of doing this would be to search for a certain package file (go.mod, requirements.txt, package.json, etc.) and then run a shell command (npm list, pip list, etc), which would not only be slow, but also open a shell session (probably has some security issues).

We can either look for a certain file or make an assumption based on the dominant language:

rust --> cargo tree
javascript --> npm list
python --> pip list

Concerning the performance hit, this will be executed asynchronously via futures - the same way we already do  for all `git `commands -, and I am pretty sure that this will give a result faster than the `git log` command required by onefetch. As a result, the overall response time won't be affected.

**Comment by Luke-zhang-04** [comment]
Awesome. I'll give it a shot

**Comment by spenserblack** [comment]
Besides using a shell command to list dependencies, you could also look into the serde crate, serde_json, etc. to deserialize package info files.
This is a basic example struct that should be able to be deserialized from `package.json`, for example.
```rust
#[derive(Deserialize)]
struct NpmPackage {
    dependencies: HashMap<String, serde_json::Value>,
    #[serde(name = "devDependencies")]
    dev_dependencies: HashMap<String, serde_json::Value>,
}
// NOTE This can be improved with zero-copy deserialization and replacing HashMaps with types that only store the keys
```
Then you can count the keys in the hash maps to get the count of dependencies.
This way you won't have to worry about error handling if the package manager isn't installed or cannot be executed. Also [deserializing in Rust can be pretty fast](https://github.com/serde-rs/json-benchmark).

Similarly, there should be a crate for parsing a `Cargo.toml` file. I think `requirements.txt` has no more than 1 dependency per line, so a line count might be sufficient, but a regex lead to more accurate results. Just looked at an example `go.mod` file, that would probably require a regex if not running a shell command.

**Comment by o2sh** [comment]
I agree, parsing the files manually might be better than relying on shell commands. It won't be async - serde doesn't handle it - but as you said: it's super fast so it won't matter as much. 

> There should be a crate for parsing a `Cargo.toml`

[toml crate](https://docs.rs/toml/0.5.7/toml/)

**Comment by Luke-zhang-04** [comment]
Alright, I'll take a look into that

**Comment by Luke-zhang-04** [comment]
Do you think we should just do one layer of dependencies or the whole dependency tree?

I.e there's package.json (explicit dependencies), and then package-lock.json (every installed package).

**Comment by o2sh** [comment]
As a first implementation, I think we can stick to explicit dependencies only.
