### ISSUE TITLE
Add JSON output support

### ISSUE THREAD

**Issue by joseluisq** [o2sh/onefetch#302]
It would be great if `onefetch` could share its stats like `Project`, `Authors`, etc in JSON format. Probably a `--json` flag for that.
I also think that [serde](https://crates.io/crates/serde) can help here.

**Comment by nguyenquannnn** [comment]
Hey @o2sh can I take a dig at this?

**Comment by HallerPatrick** [comment]
Hey, after there is not much progress on this issue, I just dived into this feature. 
So far I have a running implementation which gives following output to stdout:

```json
{
  "git_username": "Patrick Haller",
  "git_version": "git version 2.28.0",
  "repo_name": "onefetch",
  "number_of_tags": 23,
  "number_of_branches": 2,
  "head_refs": {
    "refs": [
      "master",
      "origin/master"
    ]
  },
  "pending_changes": "10+- 1+",
  "version": "v2.7.3",
  "creation_date": "2 years, 3 months ago",
  "languages": [
    [
      "Rust",
      96.36507309363887
    ],
    [
      "Python",
      2.8447254049782695
    ],
    [
      "Markdown",
      0.7902015013828527
    ]
  ],
  "dependencies": "16 (cargo)",
  "authors": [
    [
      "Ossama Hjaji",
      589,
      57
    ],
    [
      "dependabot[bot]",
      66,
      6
    ],
    [
      "Spenser Black",
      49,
      4
    ]
  ],
  "last_change": "5 hours ago",
  "repo_url": "https://github.com/o2sh/onefetch.git",
  "number_of_commits": "1021",
  "lines_of_code": 2511,
  "repo_size": "14.48 MiB (110 files)",
  "license": "MIT",
  "dominant_language": "Rust",
  "text_colors": {
    "title": {
      "TrueColor": {
        "r": 228,
        "g": 55,
        "b": 23
      }
    },
    "tilde": "White",
    "underline": "White",
    "subtitle": {
      "TrueColor": {
        "r": 228,
        "g": 55,
        "b": 23
      }
    },
    "colon": "White",
    "info": "White"
  }
}
```

I used the mentioned serde lib. This output represents the Info struct, but is omitting the used ascii colours and the cli struct.

What do you think?

**Comment by spenserblack** [comment]
Looks awesome! :smiley:

But it would probably be best if the JSON isn't a 1:1 of the Info struct.

***

- `creation_date` and `last_change`: Values like `"5 hours ago"` are "pretty", but a user outputting to JSON probably wouldn't want the pretty output, and would prefer an actual date.
- ```diff
  -"git_version": "git version 2.28.0",
  +"git_version": "2.28.0",
  ```
- `"pending_changes"` might be better as an object with `"added"`, `"modified"`, and `"removed"` keys.
- `"text_colors"` and other fields can probably be omitted, since those are config options for how the `Info` struct should be output to the terminal, not actually repo information.
- `#[serde(rename = "foo")]` can be used to output the JSON as camelCase, which I think is more common for JSON.
  ```rust
  // e.g.
  #[serde(rename = "gitUsername")]
  git_username: String
  ```
  Although `rename` might not be the best. I think there's a macro that controls *only* how serde will serialize to JSON (and other formats).

**Comment by o2sh** [comment]
Thanks for taking a shot at it @HallerPatrick.
If it's ok with @nguyenquannnn, you can create a PR - taking into account @spenserblack remarks -, and I'll be more than happy to merge it.

**Comment by nguyenquannnn** [comment]
> Thanks for taking a shot at it @HallerPatrick.
> 
> If it's ok with @nguyenquannnn, you can create a PR - taking into account @spenserblack remarks - and I'll be more than happy to merge it.

Hi please go ahead! Sorry about the delay, it's been a busy month for me

**Comment by HallerPatrick** [comment]
> Looks awesome! 😃
> 
> But it would probably be best if the JSON isn't a 1:1 of the Info struct.
> 
> * `creation_date` and `last_change`: Values like `"5 hours ago"` are "pretty", but a user outputting to JSON probably wouldn't want the pretty output, and would prefer an actual date.
> * ```diff
>   -"git_version": "git version 2.28.0",
>   +"git_version": "2.28.0",
>   ```
> * `"pending_changes"` might be better as an object with `"added"`, `"modified"`, and `"removed"` keys.
> * `"text_colors"` and other fields can probably be omitted, since those are config options for how the `Info` struct should be output to the terminal, not actually repo information.
> * `#[serde(rename = "foo")]` can be used to output the JSON as camelCase, which I think is more common for JSON.
>   ```rust
>   // e.g.
>   #[serde(rename = "gitUsername")]
>   git_username: String
>   ```
>   
>   
>   Although `rename` might not be the best. I think there's a macro that controls _only_ how serde will serialize to JSON (and other formats).

Thank you for the reply. I will take another look at it, and make it more "raw" and CamelCase.

**Comment by HallerPatrick** [comment]
Alright, had to change a little more than I wanted, but no logical changes in the original source code.

This is what I got:

```json
{
  "gitVersion": "2.28.0",
  "gitUsername": "Patrick Haller",
  "repoName": "onefetch",
  "numberOfTags": 23,
  "numberOfBranches": 2,
  "headRefs": {
    "refs": [
      "master",
      "origin/master"
    ],
    "oid": "9993dcb"
  },
  "pendingChanges": "3+- 8+",
  "version": "v2.7.3",
  "creationDate": "2 years, 3 months ago",
  "languages": [
    [
      "Rust",
      96.45881447267128
    ],
    [
      "Python",
      2.771362586605081
    ],
    [
      "Markdown",
      0.7698229407236336
    ]
  ],
  "dependencies": "16",
  "authors": [
    [
      "Ossama Hjaji",
      589,
      57
    ],
    [
      "dependabot[bot]",
      66,
      6
    ],
    [
      "Spenser Black",
      49,
      4
    ]
  ],
  "lastChange": "3 hours ago",
  "repoUrl": "https://github.com/HallerPatrick/onefetch.git",
  "numberOfCommits": "1023",
  "linesOfCode": 2578,
  "packedRepoSize": "14.48 MiB (111 files)",
  "repoSize": "14.48 MiB",
  "filesCount": 111,
  "license": "MIT",
  "dominantLanguage": "Rust",
  "textColors": {
    "title": {
      "TrueColor": {
        "r": 228,
        "g": 55,
        "b": 23
      }
    },
    "tilde": "White",
    "underline": "White",
    "subtitle": {
      "TrueColor": {
        "r": 228,
        "g": 55,
        "b": 23
      }
    },
    "colon": "White",
    "info": "White"
  }
}
```

The Info struct holds its information, which should in the end be displayed to stdout, in an already formatted displayable format. I did a mix of refactoring for more granular information and string processing to get the information  from the existing struct fields.

E.g.
From this:
```json
  "packedRepoSize": "14.48 MiB (111 files)",
  "repoSize": "14.48 MiB",
  "filesCount": 111,
```

To this:
```json
  "packedRepoSize": "14.48 MiB (111 files)",
  "repoSize": "14.48 MiB",
  "filesCount": 111,
```

For now this should work fine, but IMO the logic of already populating the Info struct with human readable information should be refactored into raw granular information fields. And leave the whole string concat and formatting logic to fmt::Display. 

Fields that could also be changed:
```json
{
  "creationDate": "2 years, 3 months ago",
  "lastChange": "3 hours ago", 
  "pendingChanges": "3+- 8+"
}
```

Also those are retrieved through git calls, which have to be altered too.

Maybe I am over engineering. If there is no use cases for a more granular Info struct, than for this feature, we can lay my suggestion at rest. :)

**Comment by spenserblack** [comment]
>IMO the logic of already populating the Info struct with human readable information should be refactored into raw granular information fields. And leave the whole string concat and formatting logic to fmt::Display.

I agree that this would probably be best if onefetch will start supporting data outputs (JSON, YAML, TOML, etc.).

>Also those are retrieved through git calls, which have to be altered too.

The git call could possibly be changed to printing a format that can be parsed into a struct (there's `chrono::DateTime`, but there might be some better options out there), then the duration is calculated for `Display`.
