### ISSUE TITLE
Add ability to ignore git submodules

### ISSUE THREAD

**Issue by d3zd3z** [o2sh/onefetch#31]
Some projects pull in other large subprojects as submodules (think of LLVM in the Rust compiler source). This can dwarf the statistics, making them less useful.

This could either be added as a feature to tokei, or use the output of a git submodule command to generate a list of exclusions to give to it.

**Comment by samblake** [comment]
O

**Comment by o2sh** [comment]
Sorry for the late answer. 
I'm not sure I see the issue, tokei (therefore onefetch) is already ignoring everything that is listed in your .gitignore file.

What I can do is add an exclude flag (like in tokei) where the user can specify some files or folder to exclude which are not referenced in the .gitignore...

Would that solve the issue?

**Comment by spenserblack** [comment]
If the tokei dependency is updated to version 10.0, you should be able to add a `.tokeignore` file \(see [tokei's `CHANGELOG.md`](https://github.com/XAMPPRocky/tokei/blob/master/CHANGELOG.md#1000)\). Without looking too much into onefetch's code, I'm assuming that, whatever tokei ignores via this file, onefetch would ignore as well. That might help with this issue.

**Comment by o2sh** [comment]
Thanks for the info @spenserblack 

Plz do the PR :1st_place_medal: 

Does that solve the issue @d3zd3z ?

**Comment by d3zd3z** [comment]
I "solves" the issue in that it provides another way to work around it. But it is at least more meaningful as a Tokei-specific file.

**Comment by spenserblack** [comment]
A PR that I'm working on (https://github.com/o2sh/onefetch/pull/1305) will actually have the side-effect of ignoring submodules by default.

Looking at `scc`, I'm starting to think that's a reasonable default, and a `--recurse-submodules`, flag can be added if there's demand.
