### ISSUE TITLE
Replace git sys calls with git2-rs

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#310]
Currently, we manage to retrieve Git repository information via two means:

* Git sys calls --> `std::process::Command::new("git").`..
* [`git2-rs`](https://github.com/rust-lang/git2-rs) -->  `git2::Repository::::discover(&config.path)`,

In order to homogenize the code and not rely on the Git binary to be present on the user's machine, we wish to update the following methods:

- get_packed_size
- get_git_history

to switch from Git sys calls to git2-rs function calls instead.

**Comment by HallerPatrick** [comment]
If my PR for #302 should be accepted then I would gladly take a look at it. I already refactored get_packed_size into more  granular functions in that PR. 
We also had  the [discussion](https://github.com/o2sh/onefetch/issues/302#issuecomment-740605221) in the thread in the same Issue, that the `struct Info` to which those git calls provide their information should be saved more "raw" (not directly in a human readable format). 
Maybe this is something that can be addressed on the fly.

**Comment by o2sh** [comment]
This one is quite tricky, but even if you only manage to migrate `get_packed_size`: that would already be a big step forward.

> We also had the discussion in the thread in the same Issue, that the struct Info to which those git calls provide their information should be saved more "raw" (not directly in a human readable format).
> Maybe this is something that can be addressed on the fly.

Sure!

Thanks for the help @HallerPatrick
