### ISSUE TITLE
Repo information picks strange remote

### ISSUE THREAD

**Issue by clux** [o2sh/onefetch#314]
If `git remote -v` has more than one remote, the one picked seems strange to me (i got a random one from an old pr).

The repo url should probably be taken from the `origin` remote if it exists.

**Comment by o2sh** [comment]
Hi @clux 
With a183a32, we now look for `remote.origin.url` as the default choice and if it doesn't exist we fallback to the first entry matching `Regex::new(r"remote\.[a-zA-Z0-9]+\.url")`

**Comment by clux** [comment]
Ah, that was quick. Thank you. That looks good to me!
