### ISSUE TITLE
Support for XAML

### ISSUE THREAD

**Issue by mike-ward** [o2sh/onefetch#317]
I see there's support for XML but it's not clear if XAML is supported.

**Comment by o2sh** [comment]
No, XAML is not currently supported by Onefetch.
Let's work on that!

**Comment by o2sh** [comment]
![xaml_wezterm](https://user-images.githubusercontent.com/13710835/99104667-930e7680-25e1-11eb-9cdb-690d9e3e4822.png)

Is this good ?

**Comment by mike-ward** [comment]
Looks great!

**Comment by mike-ward** [comment]
Thanks!
