### ISSUE TITLE
gracefully handle lack of user.name

### ISSUE THREAD

**Issue by geeseven** [o2sh/onefetch#320]
Greetings,

I get an error without user.name even when attempting to disable the git_info field.

```console
$ git config --list
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/o2sh/onefetch.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master

$ onefetch
[onefetch error]: config value 'user.name' was not found; class=Config (7); code=NotFound (-3)

$ onefetch --disable-fields git_info
[onefetch error]: config value 'user.name' was not found; class=Config (7); code=NotFound (-3)

$ onefetch --version
onefetch 2.7.2
```

I feel that the git_info field should gracefully handle the lack of user.name and just show the git version information.  Also, it shouldn't matter when you want to disable that field.

**Comment by o2sh** [comment]
I know, i just pushed a new version fixing this issue.

**Comment by geeseven** [comment]
Thanks for the timely reply.  I could have sworn I checked the commit log. :facepalm:
