### ISSUE TITLE
Omit part of display depending on terminal size?

### ISSUE THREAD

**Issue by Luke-zhang-04** [o2sh/onefetch#327]
If I open a split terminal in say VSCode, onefetch (obviously) gets really deformed
![image](https://user-images.githubusercontent.com/55749227/100295099-baa4fd80-2f56-11eb-9df4-d23a5acee4f1.png)

We can use the [term_size](https://docs.rs/term_size/0.3.2/term_size/) crate to get terminal size, and from there, omit either the ASCII logo or the insignts.

The question then becomes which one we should remove. I'm thinking logo, but I want to know what you think.

---------

- [ ] Prevent line wrap by default with `print!("\x1B[?7l")` - I'll take care of that one.
- [x] Add options to the -off CLI flag (rename it to --hide-logo) to automatically hide the art if the term_size is too small.

**Comment by geeseven** [comment]
As someone that uses a laptop with a single small resolution screen, I can sympathize with these types of issues.  Another option could be line wrapping within the insights pane.  I have no clue how difficult that might be to accomplish.

Regarding term_size, looks like it does not support TTYs.  

Should this application should even caterer to small terminals or TTYs?  :shrug:

**Comment by Luke-zhang-04** [comment]
I've never heard of TTY before, so maybe that's something for another day? It seems a bit niche. I'm just thinking we do a simple if somewhere do skip the ASCII art or something.

**Comment by o2sh** [comment]
Indeed, hiding the ascii logo if the terminal is too narrow makes sense. However, it may still be deformed if the windows' width is really small. A quick fix would be to `print!("\x1B[?7l")` in main.rs before printing the output to disable line wrap:

![2020-11-27_00-09](https://user-images.githubusercontent.com/13710835/100396343-f7e7b900-3044-11eb-9bed-82ad337e36fc.png)

without forgetting to re-enable it before exiting.

**Comment by spenserblack** [comment]
If the ASCII logo can be hidden, it should probably be something that can be controlled by a CLI option. For example, `--hide-logo`, with the possible options `auto`, `always`, or `never`.

**Comment by Luke-zhang-04** [comment]
Yeah that's a good idea

**Comment by Luke-zhang-04** [comment]
> A quick fix would be to print!("\x1B[?7l") in main.rs before printing the output to disable line wrap - as suggested by @geeseven:

I meannn what if we did both?

**Comment by geeseven** [comment]
> disable line wrap - as suggested by @geeseven 

I would like to clarify my initial suggestion.  I was thinking something like this.

![one-fetch](https://user-images.githubusercontent.com/2334728/100473704-95260a00-30a4-11eb-9688-78315fb02eb2.png)

That being said, I don't have anything against disabling line wrap.


> If the ASCII logo can be hidden, it should probably be something that can be controlled by a CLI option. For example, --hide-logo, with the possible options auto, always, or never.

There already is the `--off` option.  Maybe it just needs a better name and/or description? 

```console 
$ onefetch -h |grep '\-\-off'
        --off                          Only shows the info lines.

$ onfetch --off
unknown ~ git version 2.29.2
----------------------------
Project: onefetch (3 branches, 23 tags)
HEAD: b596d6c (vala, origin/vala)
Pending: 1+
Version: v2.7.3
Created: 2 years, 2 months ago
Languages: Rust (96.3 %) Python (2.9 %) 
           Markdown (0.8 %) 
Dependencies: 13 (cargo)
Authors: 58% Ossama Hjaji 576
         6% dependabot[bot] 60
         4% Spenser Black 49
Last change: 5 days ago
Repo: git@github.com:geeseven/onefetch.git
Commits: 992
Lines of code: 2435
Size: 14.45 MiB (109 files)
License: MIT
```

And line wrapping with `--off` seems reasonable.

![one-fetch-small](https://user-images.githubusercontent.com/2334728/100475087-d4a22580-30a7-11eb-89c2-320346fdd839.png)


After pondering over this issue a bit more,  I don't think we should spend too much effort on terminals smaller than 80 characters wide.  80x25 is an very old standard when it comes to terminal/console size.  In the modern age, this is laughable small with high resolution/DPI widescreen monitors.

**Comment by o2sh** [comment]
Sounds good!

- [ ] Prevent line wrap by default with `print!("\x1B[?7l")` - I'll take care of that one.
- [ ] Add options to the -off CLI flag (rename it to --hide-logo) to automatically hide the art if the term_size is too small.

**Comment by geeseven** [comment]
> Prevent line wrap by default with `print!("\x1B[?7l")`

Should we leave line wrap on for `--hide-logo`?

**Comment by o2sh** [comment]
I see your point. Maybe we should re-enable if `--hide-logo` is provided.

**Comment by Luke-zhang-04** [comment]
>  Add options to the -off CLI flag (rename it to --hide-logo) to automatically hide the art if the term_size is too small.
I can do this unless @geeseven wants to

**Comment by geeseven** [comment]
> I can do this unless @geeseven wants to

Feel free as Rust still looks like hieroglyphics to me. :smile:

**Comment by Luke-zhang-04** [comment]
> Feel free as Rust still looks like hieroglyphics to me. :smile:

Same here lol

**Comment by Luke-zhang-04** [comment]
#330

**Comment by spenserblack** [comment]
Can this be considered closed by #330?

**Comment by o2sh** [comment]
We're still missing:

- [ ] Prevent line wrap by default with print!("\x1B[?7l").

The main difficulty is to make sure to re-enable the line wrap when exiting the program with `print!("\x1B[?7h")`.
In bash this can be done with `trap 'printf "\e[?7h"' EXIT` like that even if the program is killed or interrupted the command will be executed. I'm trying to find smth similar in Rust.

**Comment by spenserblack** [comment]
Perhaps a combination of [signal hooks](https://docs.rs/signal-hook/0.2.1/signal_hook/) and [panic hooks](https://doc.rust-lang.org/std/panic/fn.set_hook.html)?

**Comment by Luke-zhang-04** [comment]
I think this is probably out of the scope of my abilities, especially since Rust is such a foreign language to me. If I was supposed to do something here then sorry for not saying something earlier but I don't think I can.

**Comment by o2sh** [comment]
I'm the one who was supposed to work on that second part :disappointed:.
Unfortunately, last time I tried, I wasn't able to come up with an elegant/robust solution to **make sure** to re-enable the line wrap before exiting the program - **in all cases** -, and not risking to mess up with the user's terminal configuration.
