### ISSUE TITLE
[onefetch error]: please run onefetch inside of a non-bare git repository

### ISSUE THREAD

**Issue by strogiyotec** [o2sh/onefetch#335]
Good day. I just installed onefetch using snap store and when I run `onefetch` within git repository I am getting this output
```
❯ onefetch
ERROR: ld.so: object '/lib/x86_64-linux-gnu/liboneagentproc.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/x86_64-linux-gnu/liboneagentproc.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/x86_64-linux-gnu/liboneagentproc.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/x86_64-linux-gnu/liboneagentproc.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
[onefetch error]: please run onefetch inside of a non-bare git repository
```
I don't use bare repository and it behaves in the same way with other repos . My version is `onefetch 2.7.3`. My OS is ` OS: Ubuntu 18.04.5 LTS x86_64`.
Git status within the same directory shows 
```
❯ git status
On branch main
Your branch is up to date with 'origin/main'.
```
How can I solve it ? Thanks in advance

**Comment by spenserblack** [comment]
:thinking: Would you be willing to try compiling onefetch@2.7.3 and see if you get a compiler error?

`cargo install onefetch --version 2.7.3 --debug`

**Comment by strogiyotec** [comment]
Sure , I don't have cargo and rust runtime , will install and let you know if error is still there

**Comment by strogiyotec** [comment]
@spenserblack  building with cargo resolved my problem so I assume that version from snap store is broken, should I close the ticket ?

**Comment by hentai-chan** [comment]
@strogiyotec it's better to leave this ticket open until the snap store version resolves this issue

**Comment by spenserblack** [comment]
@strogiyotec I'm glad that the `cargo install` worked :smile:
I'll have to research this a bit more, since I'm not too familiar with snaps or ld, but I'm thinking that maybe a shared library in your environment is in a different location than it was for the environment where the snap store version was compiled, resulting in the `cannot open shared object file` error.

**Comment by aliceTheGrinseCatz** [comment]
> thinking Would you be willing to try compiling onefetch@2.7.3 and see if you get a compiler error?
> 
> `cargo install onefetch --version 2.7.3 --debug`

Doesn't work for me (Pop!_OS 21.10). I tried the command with the newest as well as with the version 2.7.3 and I still get the error "[onefetch error]: please run onefetch inside of a non-bare git repository". I installed as it is described. The snap version give me the same output and even the version from the official ppa doesn't work. I decided to install it directly from the source and now, it works.
