### ISSUE TITLE
Misleading Size Label

### ISSUE THREAD

**Issue by HallerPatrick** [o2sh/onefetch#338]
While working on #310 I stumbled on `get_repo_size` which uses a the os git command  `git -C <dir> count-objects -vH` to determine the *current* size of the git repo.

Il explain why this is misleading:

|                        | onefetch w/o `.git` |  `.git`             | Total |
| ------------- | -------------           |------------- | ------------- |
| Size                |  1.8 MiB                    |  15M              | 17M  |
| File Count     | 111                            | 25                  | 136  |

The git command also includes the size of `.git`, while the file count excludes `.git`. 

So we should either fix the repo size or fix the file count or add one of the others as additional information.

**Comment by o2sh** [comment]
Thanks for pointing that out @HallerPatrick.
Personally, I don't mind excluding `.git` folder when reading the `repo size`. Especially, if it allows to have more coherent values in regard to the `file count`.

**Comment by HallerPatrick** [comment]
I am doing the migration to git2 and working on this. If it is okay I would change it on the fly with Issue #310 @o2sh ?

**Comment by o2sh** [comment]
Sure, that would be great :+1:

**Comment by subnut** [comment]
@HallerPatrick Is this the reason of #342 ?
FYI, there are 15 files, and the size excluding `.git` is definitely not 0 bytes

**Comment by HallerPatrick** [comment]
> @HallerPatrick Is this the reason of #342 ?
> FYI, there are 15 files, and the size excluding `.git` is definitely not 0 bytes

Its probably not the reason.
