### ISSUE TITLE
Should the logo have a white background?

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#339]
GitHub now has an official dark theme. When using the dark theme, `onefetch.svg`'s text is hard to read due to the low contrast between the black text and the dark (`#30363d` if I'm reading the CSS correctly) rendered README background.

**Comment by o2sh** [comment]
The "least" ugly solution I found was to make the logo a little brighter (black --> dark grey).

**Comment by spenserblack** [comment]
Still looks readable on light background, but is now more readable on dark background. Thanks! :smile: 

It still looks *better* on a light background IMO, but I think that's about as good as we're going to get :slightly_smiling_face:
