### ISSUE TITLE
I made homebrew formula

### ISSUE THREAD

**Issue by Cj-bc** [o2sh/onefetch#34]
I made a homebrew formula for this: [Cj-bc/homebrew-onefetch](https://github.com/Cj-bc/homebrew-onefetch) 
Actually it's not so good(ex: doesn't use 'make' to install), but It should work.
I wonder this helps someone ;)

**Comment by o2sh** [comment]
This is much appreciated @Cj-bc,
I don't use MacOS, so I can't test it.
If this works, it will resolves #21.

The next big step would be to do a PR to the homebrew-core repository in order to add onefetch as a formula.

Can you do that ?

Thanks again.

**Comment by Cj-bc** [comment]
Thanks for the comment!
First of all, as I'm not a native English speaker, there could be lots of mistakes. Sorry about that.

### about #21

Actually, I think this doesn't resolve #21 unless the formula added to homebrew-core because it won't provide any binaries for now.
We should compile onefetch on our computer.
(But when it's added to homebrew-core, they would make binaries, `bottle`, for us)

### PR to homebrew-core

I'm thinking those could be problems to submit PR:
- lack of test in the formula
- I don't use `Makefile` to install
- Does it meet [Acceptable Formula](https://docs.brew.sh/Acceptable-Formulae)

#### lack of test in the formula

This is just because I'm not good at Rust(so I even don't know whether this repo has test or not).
If there's some test, I can add them.

#### Doesn't use `Makefile`

That's because, when I used it, the build failed.
I'm not sure whether this will be the reason for rejection, but I know that's not a good idea not to use `Makefile` although it provided officially.


#### Does it meet Acceptable Formula

[The official page](https://docs.brew.sh/Acceptable-Formulae) says that
Niche (or self-submitted) stuff must:

- be known
- be used
- have a homepage

I think the top 2 of them are passed, but I don't know how they judge them.

The third one, `have a homepage` could be the big problem.
I'm wondering is Github page accepted for that purpose?

**Comment by o2sh** [comment]
OK so first, we need the binary for MacOS --> If you can build the project with rustc you should be able to provide me with the binary which I will then attach to the current release. After that you should update the formula with the proper file.

------

About the Makefile --> here is a brew formulae for a rust project (which is a dependency of onefetch) that doesn't use a Makefile and has a boilerplate test and no homepage beside the GH repo.

I think we're almost there, what do you think ? @Cj-bc

**Comment by Cj-bc** [comment]
Here's binary file for MacOS Mojave 10.14.4
It's compiled by doing `cargo build --release`

[onefetch_macosx_mojave_x86-64.zip](https://github.com/o2sh/onefetch/files/3175435/onefetch_macosx_mojave_x86-64.zip)


---

Thanks for the reference!
It helps a lot.

Previous Todo:

- [ ] lack of test in the formula
- [x] don't use Makefile to install
- [x] Homepage

I'm working on making tests...
So I think we're almost there, too.

Nothing will happen if we don't dive in, so why not try ?!

**Comment by o2sh** [comment]
Having trouble compiling the project @Cj-bc ?

**Comment by Cj-bc** [comment]
yes, I think something wrong happens with that. Compiling was done with no problem.
But when I see the binary with 'strings', there were some error messages(for human read) which contains some environment variables, paths, etc.
I've heard that some error message could be included, but I think that's too strange...
(I asked my friend who can write Rust. He said it's not common case to have paths in the binary.)

---
And I'm stuck with making test right now.
I planned to compare current output of `onefetch` with prepared output( which we know it's correct).
But I have no idea how to:
- manipulate git from ruby
- compare two outputs ( maybe I can do this by using `system "diff", <prepared output>, <current output>`?)

I think best solution for this is just throw away that plan and switch to just display version of onefetch ( some formula did, I think) 
When we do so, I can submit PR to homebrew-core in few days.

**Comment by o2sh** [comment]
Alright, Good luck with that @Cj-bc !

And thanks for your contribution

**Comment by o2sh** [comment]
So, you gave up @Cj-bc ?
Too bad, that was a great idea...

:cry:

**Comment by Cj-bc** [comment]
Sorry for late reply, I've worked on other work...
I don't mean give up, though.

Actually, I'm stucking with making test.
I realize that there's no way to output version information. So I can't check version as test.
And other idea, which is to compare current outputs with prepared outputs ( like snapshot test? I think.), wasn't work good for now. I've got an error from homebrew. As I'm not good at Ruby(Actually I never wrote anything but homebrew formula), I have no idea what to do next.

**Comment by o2sh** [comment]
Ok , just use a boilerplate test for now, example :

  test do
    (testpath/"lib.rs").write <<~EOS
      #[cfg(test)]
      mod tests {
          #[test]
          fn test() {
              println!("It works!");
          }
      }
    EOS
    system bin/"tokei", "lib.rs"
end

we will improve on it later on.

If you could just provide with the binary for MacOs, I can do the rest.

Thanks again for everything @Cj-bc

**Comment by Cj-bc** [comment]
Sorry I'm wondering some misunderstanding occur?
(If that's my mistake, sorry for that. I'm not familiar to boilerplate test.)

I think `tokei`'s example is good for them because it actually tests features of `tokei`.
But I think we can't do any test which tests features of `onefetch` without git repository. ( And when I try to manipulate git, I've got some error.)

### The test I was planned:

#### Preparing part: 
1. generate onefetch output for the specific commit of the onefetch repository.
2. Put that into the formula.

#### Test:
1. Copy onefetch repository under `testpath`(so that we can change commit to testing safely)
2. Checkout a commit that is the same as we used before in `Preparing part, 1`
3. Generate onefetch output. Store it.
4. Compare `3.` output with `Preparing part,2`.
5-1. If there're no diffs, then the test will succeed.
5-2. If not, the test will fail.

---

# about mac binary
Sorry, but I can't publish binary till a problem be fixed.
I'll explain what happens.
When I use `strings(a command that outputs binary as strings as possible)` to check binary which I've compiled, there're some error messages included, and what is worse, some private things(ex: part of PATH) are also included. (The picture below only contains safe things to show)
I don't want to publish such info.

**Comment by achikin** [comment]
Any updates on this?

**Comment by erikgaal** [comment]
@achikin There is a Formula available in `homebrew-core` now!
