### ISSUE TITLE
Adding Pub, the Dart package manager,   to package managers

### ISSUE THREAD

**Issue by HallerPatrick** [o2sh/onefetch#344]
While the dart programming language is supported, the [pub package manager](https://pub.dev) is not. 

It is standardised with a `pubspec.yaml`file with a `dependencies`section see here: https://dart.dev/tools/pub/pubspec#dependencies

**Comment by HallerPatrick** [comment]
If you, @spenserblack and/or @o2sh, do not have something against this, then I would assign this issue to myself.

**Comment by o2sh** [comment]
Sure :100:
