### ISSUE TITLE
Include look up for dependencies in pyproject.toml

### ISSUE THREAD

**Issue by HallerPatrick** [o2sh/onefetch#345]
Not all python projects use requirements.txt anymore. With [PEP 518](https://www.python.org/dev/peps/pep-0518/) and [PEP 621](https://www.python.org/dev/peps/pep-0621/) pyproject.toml also allows for defining build dependencies. This is e.g used by [Poetry](https://github.com/python-poetry/poetry). 

I would not necessarily include Poetry as a dependency manager, but if a `requirements.txt`is not provided, then look for a `pyproject.toml`. All dependencies are then defined under a [`[tool.poetry.dependencies]`](https://python-poetry.org/docs/dependency-specification/) or [`[dependencies]`](https://www.python.org/dev/peps/pep-0621/#dependencies-optional-dependencies) section.

**Comment by spenserblack** [comment]
To add onto this, [pipenv](https://pypi.org/project/pipenv/) creates a `Pipfile` with a `[packages]` section. It seems to follow TOML format.
