### ISSUE TITLE
Enhancement: Add .axaml files to Xaml language detection

### ISSUE THREAD

**Issue by mike-ward** [o2sh/onefetch#348]
Avalonia has a Xaml dialect that uses a `.axaml` extension to avoid collisions with Visual Studio's Xaml designer. It's still Xaml, just a different flavor.

**Comment by o2sh** [comment]
Hi @mike-ward,
FYI onefetch relies entirely on [tokei](https://github.com/XAMPPRocky/tokei) for language detection. So, there isn't much we can do here, you should therefore create an issue on their repo.

**Comment by mike-ward** [comment]
good to know.
