### ISSUE TITLE
Support for QML

### ISSUE THREAD

**Issue by mapau** [o2sh/onefetch#361]
# QML

https://doc.qt.io/qt-5/qmlapplications.html

## Logo
https://github.com/QMLCommunity

## Upstream support

- [x] [tokei] supports this language

[tokei]: https://github.com/XAMPPRocky/tokei

**Comment by mapau** [comment]
Hi, I added the qml support to language.rs file to my fork
https://github.com/mapau/onefetch/tree/feature/add-qml-support

https://github.com/Aaronepower/tokei already detects the qml files only the mapping in onefetch is missing.

Would be my first contribution to any GitHub Project.

**Comment by spenserblack** [comment]
>Hi, I added the qml support to language.rs file to my fork

Great! Would you like to make a pull request?

**Comment by mapau** [comment]
https://github.com/o2sh/onefetch/pull/362

**Comment by o2sh** [comment]
> Didn't know about the cargo test. Sorry it's my first steps with rust and the tools around it.

You're doing great! looking forward to merge your PR :+1: 

> I'll fix the ascii file and Update the PR, or should I create a new pull-request?

Just update it.
