### ISSUE TITLE
Support for Nim

### ISSUE THREAD

**Issue by icyphox** [o2sh/onefetch#37]
Hey, it’d be cool to have support for the Nim programming language. 
https://github.com/nim-lang/nim

**Comment by o2sh** [comment]
Hi @icyphox,
Tell me what you think? (and close if OK)

![DeepinScreenshot_select-area_20190622111352](https://user-images.githubusercontent.com/13710835/59963173-feccdc80-94de-11e9-9b1b-14797554f864.png)

Thanks for the suggestion!

**Comment by icyphox** [comment]
This looks great! Thanks :)
