### ISSUE TITLE
Last change: now ago

### ISSUE THREAD

**Issue by planet36** [o2sh/onefetch#377]
`onefetch 2.9.1`

Very shortly after making a commit and then running onefetch, the "Last change" shows "now ago".

`Last change: now ago`

The word "ago" should be omitted if the delta time is close enough to be "now" because it doesn't sound right.

**Comment by o2sh** [comment]
I agree, it does sound a bit clumsy :grimacing:

onefetch relies on [chrono_humanize](https://crates.io/crates/chrono-humanize) for its time formatting.

Looking at this [issue](https://gitlab.com/imp/chrono-humanize-rs/-/issues/7), it should be easily fixable by replacing these [two lines ](https://github.com/o2sh/onefetch/blob/60e554f8e560ba12409f819d7765b4f06d464983/src/onefetch/utils.rs#L46-L47) with:

```rust
let ht = HumanTime::from(dt_with_tz);
format!("{}", ht)
```
