### ISSUE TITLE
Support for Dart

### ISSUE THREAD

**Issue by MaterialTime** [o2sh/onefetch#38]
Could support for the [Dart](https://dart.dev) programming language be added?

Adding Dart support would also make this program compatible with repositories containing [Flutter](https://flutter.dev) apps.

**Comment by o2sh** [comment]
Hi @MaterialTime,
Tell me what you think? (and close if OK)

![DeepinScreenshot_select-area_20190622105115](https://user-images.githubusercontent.com/13710835/59962941-c5df3880-94db-11e9-8267-c650a5c92d1b.png)

Thanks for your suggestion!

**Comment by MaterialTime** [comment]
@o2sh Looks good!
