### ISSUE TITLE
Automatic Homebrew release failing

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#381]
Since the merge of #160, none of the automatic homebrew release via [Github CI have succeeded](https://github.com/o2sh/onefetch/actions?query=workflow%3Ahomebrew-update-formula). 

From the logs:

```
Error: You need to bump this formula manually since changing the
version from 2.7.3 to v2.9.1 would be a downgrade.
```

@erikgaal, any idea why ?

**Comment by spenserblack** [comment]
Pinned this so it stays open
