### ISSUE TITLE
Support for Perl

### ISSUE THREAD

**Issue by tomasbargut** [o2sh/onefetch#39]
Hello, there!
Could support for Perl be added?

**Comment by o2sh** [comment]
Hi @tomasbargut ,
Tell me what you think? (and close if OK)

![DeepinScreenshot_select-area_20190714111328](https://user-images.githubusercontent.com/13710835/61182863-f91f6e00-a628-11e9-9856-8e9b3e1b928f.png)

Thanks for your suggestion!

**Comment by tomasbargut** [comment]
Awesome!
