### ISSUE TITLE
Add Name of current Local Branch and Disk Size

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#41]
We would like to display the name of the current local branch as part of the project information.
Same thing for the disk size of the Project (tip: git count-objects -vH).

Feel free to be creative in the way you want to display those infos (espacially the branch).

:)

**Comment by nikofil** [comment]
Hey! I found this issue through the hacktoberfest tag and would like to work on it. :)

**Comment by o2sh** [comment]
Sure, go ahead! 💯 

Thx @nikofil
