### ISSUE TITLE
Support for fetching remote repositories

### ISSUE THREAD

**Issue by gbaranski** [o2sh/onefetch#419]
Hello, what do you think about that? Command for that could look like that
```bash
onefetch --github o2sh/onefetch
```
Or instead --github, --remote
```bash
onefetch --remote o2sh/onefetch
```

**Comment by HallerPatrick** [comment]
Would the remote repo then be cloned beforehand? And if yes, in a temporary folder or at the current working directory?

onefetch already uses git2, which also supports cloning, so the implementation would be easy. Would love to help out with this.

**Comment by gbaranski** [comment]
> Would the remote repo then be cloned beforehand? And if yes, in a temporary folder or at the current working directory?
> 
> onefetch already uses git2, which also supports cloning, so the implementation would be easy. Would love to help out with this.

Yes, it would be cloned, on unix systems we can use /tmp for storing the repository, no idea how to do that for windows.

**Comment by HallerPatrick** [comment]
> > Would the remote repo then be cloned beforehand? And if yes, in a temporary folder or at the current working directory?
> > onefetch already uses git2, which also supports cloning, so the implementation would be easy. Would love to help out with this.
> 
> Yes, it would be cloned, on unix systems we can use /tmp for storing the repository, no idea how to do that for windows.

I think windows uses `%localappdata%\Temp`. Not really sure tho. Would the git repo afterwards be deleted? And if not, would a new `onefetch --remote <same-repo>` clone it again into temp or use the existing one?

**Comment by gbaranski** [comment]
> > > Would the remote repo then be cloned beforehand? And if yes, in a temporary folder or at the current working directory?
> > > onefetch already uses git2, which also supports cloning, so the implementation would be easy. Would love to help out with this.
> > 
> > 
> > Yes, it would be cloned, on unix systems we can use /tmp for storing the repository, no idea how to do that for windows.
> 
> I think windows uses `%localappdata%\Temp`. Not really sure tho. Would the git repo afterwards be deleted? And if not, would a new `onefetch --remote <same-repo>` clone it again into temp or use the existing one?

On Linux /tmp directory is stored in RAM, so that should be deleted automatically after restart. On windows, no idea. I've used https://doc.rust-lang.org/std/env/fn.temp_dir.html for retrieving temp directory. 

That's how it works now
![image](https://user-images.githubusercontent.com/34353640/116987122-f5ae1880-acce-11eb-92c3-61ba9cbebdc8.png)

**Comment by spenserblack** [comment]
You may also want to look into the [`temp-dir`](https://crates.io/crates/temp-dir) crate, which provides a struct that will delete the directory's contents when it is dropped.

**Comment by spenserblack** [comment]
I'm going to have to think about this feature a bit. It sounds cool, but I wonder if it's worth it when the user can just
1. `git clone <my-url> <my-dir>`
2. `onefetch <my-dir>`
3. `rm -rf <my-dir>` (if necessary)

**Comment by GameKyuubi** [comment]
Is it absolutely necessary to clone the whole repo to get the data?  Would it be impossible to get the data directly from github or smth?

**Comment by spenserblack** [comment]
Without cloning, much of the info would still be available via the GitHub API. but it's been discussed a few times if onefetch should fetch data from the API, and concluded that onefetch shouldn't be an offline-only tool.

See https://github.com/o2sh/onefetch/issues/24#issuecomment-455911188, https://github.com/o2sh/onefetch/issues/63#issuecomment-539234924, and https://github.com/o2sh/onefetch/issues/351#issuecomment-748604104

**Comment by GameKyuubi** [comment]
Perhaps, since it already supports exporting JSON, it could also *import* JSON, so that it *could* be used in a chain with a program that does all that data collection separately?

**Comment by spenserblack** [comment]
Honestly, if onefetch was going to give that level of ability to define your own statistics, it would probably be through more command-line options instead of consuming JSON. The main reason would be to prevent duplication of efforts by supporting stats via flags *and* JSON input.

If onefetch consumed JSON, it would almost be better design to split onefetch into multiple tools IMO. A tool that generates standardized JSON from GH API, a tool that generates standardized JSON from local repo, and a "front end" that consumed the data for pretty terminal output. Which sounds fun, but should be a new project instead of a change to onefetch IMO.

I think that, mainly, @o2sh created onefetch to be "[neofetch](https://github.com/dylanaraps/neofetch) for your repo." He can clarify more on the intent, but I think anything beyond more command flags is considered out of scope.
