### ISSUE TITLE
Add GDScript/Godot support

### ISSUE THREAD

**Issue by djalexkidd** [o2sh/onefetch#428]
https://godotengine.org

Godot Engine uses .gd files for scripts.

**Comment by o2sh** [comment]
<img width="839" alt="Screenshot 2021-05-24 at 02 02 38" src="https://user-images.githubusercontent.com/13710835/119281014-3943d480-bc34-11eb-9586-82ba6f399798.png">

**Comment by djalexkidd** [comment]
Thanks I like it !
