### ISSUE TITLE
Ubuntu 21.04 release

### ISSUE THREAD

**Issue by FlyinPancake** [o2sh/onefetch#440]
Hi I'd like to have Ubuntu 21.04 hirsute in the PPA or the command in the Installation documentation should be updated. 

For now the workaround is adding the ppa using the command:
``` sh
# add-apt-repository ppa:o2sh/onefetch
```
After that I can go and edit `/etc/apt/sources.d/o2sh-ubuntu-onefetch-RELEASE.list` and change `hirsute` to `groovy` there.

**Comment by o2sh** [comment]
I've just added the binary for `hirsute` 
![2021-06-02_00-12](https://user-images.githubusercontent.com/13710835/120396696-4d27be80-c337-11eb-8625-1167d782bb7e.png)

Sorry for your trouble @FlyinPancake

**Comment by FlyinPancake** [comment]
Very cool man, thanks :smile: 

working just fine now
```
Get:12 http://ppa.launchpad.net/o2sh/onefetch/ubuntu hirsute/main i386 Packages [472 B]
```
