### ISSUE TITLE
Translate README.md in Russian 🇷🇺

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#442]
It would be great to have a multiple translations of the [`README.md`](https://github.com/o2sh/onefetch/blob/master/README.md) in order to make it more accessible for non English-speaker to use the tool. These translations will be accessible directly from the English `README.md` via hyperlinks and placed in the `docs` folder.

If you're a native Russian-speaker :ru: and are willing to help, your contribution would be more than appreciated :100:

**Comment by Vinegret43** [comment]
I'm a native Russian speaker and also know English quite well, i think i'll try to do this. I'm absolutely new to this project, is there anything i should know before contributing? Also if you need translations for other files (Documentation, for example), please let me know, i'm always glad to help

**Comment by Vinegret43** [comment]
I have a question. Look at this paragraph:
```
It automatically detects open source licenses from texts and
provides the user with valuable information like code distribution,
pending changes, ...
```
What does "code distribution" mean? Does it mean percentage of every language in a repo? This can be translated in many different ways without context

**Comment by o2sh** [comment]
> What does "code distribution" mean? Does it mean percentage of every language in a repo?

Correct, I meant to refer to this info line: 

![cd](https://user-images.githubusercontent.com/13710835/132137521-2288efeb-3084-46cd-862e-24525edbda83.png)

Looking forward to see your  translation added to the project :muscle:
