### ISSUE TITLE
Ignore [bot] commits 🤖🤖

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#446]
With the democratization of dependency management bots and other non-human commit-generating tools, commit logs can get very noisy.

It would be nice to have an option for filtering these types of commits out via a CLI flag `--no-bots`. A simple approach would be to skip all commits whose author's name includes  the string `[bot]`.

**Comment by spenserblack** [comment]
Good idea! While it's common for bots to contain the string `[bot]`, I think it might be a good idea if this CLI option could take (but not require) a regex pattern. For example the user could do `onefetch --no-bots` for basic usage, or 
`onefetch --no-bots="\[[Bb]ot\]"` for more complex usage. The option's default could be `\[bot\]`.

Then onefetch could skip any commit where the author matches that regex.

**Comment by o2sh** [comment]
Absolutely! A CLI flag that accepts a pattern input but defaults to [bot].

**Comment by spenserblack** [comment]
Note for potential contributors: Looks like you explicitly have to set `min_values(0)` and `max_values(1)` to get an arg to *accept* a value, but not require it. So the `Arg` would probably look something like.
```rust
Arg::with_name("no-bots")
    .long("no-bots")
    .min_values(0)
    .max_values(1)
    .value_name("regex")
    .help("Ignore bots. Use ignore-bots=<regex> to override the default pattern.")
````
Then you could set the value like so:
```rust
let bot_pattern = matches.value_of("no-bots").unwrap_or(r"\[bot\]");
```

***

Setting `default_value` seems to cause `matches.is_present` to always to return true, even *if the user didn't use it as a CLI arg*.
