### ISSUE TITLE
Merge duplicate contributors 👤👤👤👤

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#447]
Since @yoichi's PR #243: we identify each contributor by their email address instead of their username which is definitely the right solution. However in some cases, a user may have changed his GH email along the way and therefore appear twice - or more - in the `Authors` section: 

<img width="738" alt="Screenshot 2021-06-18 at 21 48 25" src="https://user-images.githubusercontent.com/13710835/122609847-f0d6d580-d07e-11eb-9716-3207d538a7f9.png">

It may be a good idea to have a second pass in [`get_authors`](https://github.com/o2sh/onefetch/blob/aa80dc96cd9a94940ccbba5f1160ca3adc69523b/src/onefetch/repo.rs#L53) and merge the lines that share the same `username.to_lowercase()`

**Comment by HallerPatrick** [comment]
Sounds like a good idea to me.I would be interested in doing this.  @o2sh is it still open?

**Comment by o2sh** [comment]
It's all yours :thumbsup:

**Comment by HallerPatrick** [comment]
@o2sh While currently working on this, I am asking myself, why it is the better way to identify by email in the first place and not the username, when only the email can change and not the username? Or am I missing something?

**Comment by o2sh** [comment]
You can actually also change your GitHub username, even though it's less common. 

The username/email that appears in the `git log` (and parsed by onefetch) is taken from the `.gitconfig`, so if your SSH key is properly configured: you can actually put whatever you want in their and still be able to push to your repository, - or in HTTPS, if you login with username/password. On GitHub, each commit is linked to an account based solely on its email adress(es). 

I agree that merging based on the email seems arbitrary but so it is if we used the username, both give unsatisfactory results. Hence the second pass.

**Comment by HallerPatrick** [comment]
Alrighty, that seems reasonable 👍

**Comment by spenserblack** [comment]
To add on to this, most tools that I'm familiar with use the email instead of the name to identify the committer. GitHub does this, for example. Check out [this test commit](https://github.com/spenserblack/test-repo/commit/5324628a2f7fe93f1bbefefbac6bcde931b6026c), where I used the same email but a different name. GitHub still identifies me as the committer.
So I think that identifying by email is more consistent with other tools that people use.

**Comment by HallerPatrick** [comment]
Made a pull request. It is still not perfect, because there are also commits with a different username _and_ email. We would have to make guesses, if they are the same person, where I would refrain from...

<img width="735" alt="Screenshot 2021-06-26 at 15 02 28" src="https://user-images.githubusercontent.com/22773355/123513803-8847b400-d68f-11eb-9501-8fb47e2934f2.png">

**Comment by yoichi** [comment]
Git has a mechanism for identifying users by .mailmap file. Is that not enough?

**Comment by o2sh** [comment]
To be honest, I wasn't even aware that Git provided such a mechanism. 

For repositories that do provide this file, this would definitely solve our issue. Git2 seems to provide bindings to take advantage of [Mailmap](https://docs.rs/git2/0.13.20/git2/struct.Mailmap.html).

Maybe, we should explore that solution, it may result in a cleaner logic and prevent us from making any wrong assumptions on whether or not  an entry is a duplicate.

What do you think @HallerPatrick @yoichi @spenserblack 

--------

Some repositories using `.mailmap`: [linux](https://github.com/torvalds/linux), [react](https://github.com/facebook/react),  [tokei](https://github.com/XAMPPRocky/tokei), [zulip](https://github.com/zulip/zulip)

**Comment by spenserblack** [comment]
Thank you for letting us know about that, @yoichi!

@o2sh I like this approach. Would the merging by author name still be necessary? Or should we merge only on email and leave the responsibility to the repo owner to add a `.mailmap` to let onefetch know how to merge users?

**Comment by o2sh** [comment]
> Or should we merge only on email and leave the responsibility to the repo owner to add a .mailmap to let onefetch know how to merge users?

This I think, which implies reverting #449 and adding a `Mailmap` routine on top of what is currently in place.

**Comment by HallerPatrick** [comment]
But isn't `mailmap`are features not used often? @o2sh  mentioned some, but they are comparatively huge projects with a lot of commiters. Wouldn't it be better to check if a `.mailmap` file exists in root and use the routine and otherwise merge by mail?

**Comment by o2sh** [comment]
This is what I meant when I said:

> adding a `Mailmap` routine **on top of** what is currently in place.

We should keep merging by email no matter what and **if** a `.mailmap` is present, use it to merge any duplicates.

------
For example, let say we have the following logs:

```
commit 1: john <john@me.com>
commit 2: John Smith <john@me.com>
commit 3: john S. <john@gmail.com>
```


Without changing anything from what is currently in place, onefetch would be able to merge commit 1 and 2 and outputs something like:

John Smith 2
John S. 1

Now, let's assume we have the following .mailmap:

```
John Smith <john@me.com>  <john@gmail.com>
```

If we add a function that can read a .mailmap and be ran after merging by email, we would have:

John Smith 3

**Comment by HallerPatrick** [comment]
@o2sh You have a point here with the 100% correctness. I mean what we could do is another command line flag which allows for assumptions to merge by email and also write in the docs, that maintainers of their repo could include a `.mailmap` file for a clean resolution of commits.

**Comment by o2sh** [comment]
> ...write in the docs, that maintainers of their repo could include a .mailmap file for a clean resolution of commits.

Ok for the docs, not so much about adding a command line flag.

I think we should stick to what `git shortlog` does - as the de facto standard - and merge entries based on `username + email` by default with .mailmap mapping if present.

Something in the line of the [`read_from_stdin`](https://github.com/Andersbakken/git/blob/83232e38648b51abbcbdb56c94632b6906cc85a6/builtin/shortlog.c#L123) function in [shortlog.c](https://github.com/Andersbakken/git/blob/master/builtin/shortlog.c) that relies on [`parse_stdin_author`](https://github.com/Andersbakken/git/blob/83232e38648b51abbcbdb56c94632b6906cc85a6/builtin/shortlog.c#L100) for the .mailmap matching.
