### ISSUE TITLE
Support for installation using MacPortss

### ISSUE THREAD

**Issue by manojkarthick** [o2sh/onefetch#457]
Hi! Thanks for creating this tool. I noticed that it was missing from the MacPorts package manager on macOS, so I added the package. You can take a look at https://ports.macports.org/port/onefetch/summary for more details.

It can be installed using the following commands:

```
sudo port selfupdate
sudo port install onefetch
```

I was unsure how to update the wiki with this information. Could you please guide? Thanks!

**Comment by o2sh** [comment]
Thanks a lot @manojkarthick :100: 

Concerning your question about the wiki, updating the [installation page](https://github.com/o2sh/onefetch/wiki/Installation) is very simple: just follow this [example](https://github.com/o2sh/onefetch/wiki/Installation/_compare/23fb3bc2ab97df4f0ce09a7d61e7ea2e5d3eb0eb...78db90f7b42658b5e0634fd029138aa67d6a730e).

**Comment by manojkarthick** [comment]
Thank you! I've updated the wiki page. https://github.com/o2sh/onefetch/wiki/Installation#macos-macports
