### ISSUE TITLE
New Language Request: [SQL]

### ISSUE THREAD

**Issue by flowHater** [o2sh/onefetch#462]
### \[SQL\]

Currently, SQL doesn't appears in list of used language in my project.
what onefetch shows me:
![image](https://user-images.githubusercontent.com/45258763/124887429-7510de80-dfd5-11eb-9ad1-0fe55f7d89ac.png)
What tokei returns:
![image](https://user-images.githubusercontent.com/45258763/124887560-91ad1680-dfd5-11eb-991b-ce1a28d97c08.png)

### Upstream support

- [X] [tokei] supports this language

[tokei]: https://github.com/XAMPPRocky/tokei

**Comment by LordMZTE** [comment]
What logo should we use for SQL? There doesn't seem to be one official logo, but I might be mistaken.

**Comment by spenserblack** [comment]
I've been thinking about that a bit. I'm kind of fond of something like this: [![database icon](https://raw.githubusercontent.com/vorillaz/devicons/ba75593fdf8d66496676a90cbf127d721f73e961/!SVG/database.svg)](https://github.com/vorillaz/devicons/blob/ba75593fdf8d66496676a90cbf127d721f73e961/!SVG/database.svg)

It's not specific to any version of SQL (MSSQL, SQLite, etc.), and I've seen icons similar to it representing databases and SQL.

**Comment by o2sh** [comment]
Based on @spenserblack suggestion:

![sql](https://user-images.githubusercontent.com/13710835/134785125-9cac3510-d6d3-4597-aa86-469de085c75f.png)

**Comment by spenserblack** [comment]
Closed by #491
