### ISSUE TITLE
Discover hidden files and directories

### ISSUE THREAD

**Issue by 0x20F** [o2sh/onefetch#464]
Would it be possible to make onefetch look through hidden directories inside a repository?

I have a directory in one of my repositories that is hidden (starts with a dot `.system`) and onefetch doesn't find any code in the repository, however, if I unhide that directory `mv .system system` it finds all the code inside. 

Which is why I'm assuming the issue is with hidden items.

**Comment by spenserblack** [comment]
[Looks like there's a tokei config option for that](https://docs.rs/tokei/12.1.2/tokei/struct.Config.html#structfield.hidden). If you would like to make a PR, [here's where `hidden` is set to false (via `default`)](https://github.com/o2sh/onefetch/blob/f352e98f2068a00661c57657c8690f88b46e2ed5/src/info/language.rs#L346) 🙂

**Comment by 0x20F** [comment]
I'll gladly make a PR when I've got a bit of time, thank you!
