### ISSUE TITLE
New Language Request: [Protocol Buffers]

### ISSUE THREAD

**Issue by 0rax** [o2sh/onefetch#467]
### \[Protocol Buffers\]

Protocol Buffers files are usually used to define the data modeling and when paired with [gRPC](https://grpc.io/) the API method of a service. They are then used to generate code in the native language they will be used and are a substantial part of some codebase (5% in my case).

### Logo

![Protobuf Logo](https://img.stackshare.io/service/4393/ma2jqJKH_400x400.png)

### Upstream support

- [x] [tokei] supports this language

[tokei]: https://github.com/XAMPPRocky/tokei

**Comment by HallerPatrick** [comment]
Hey @0rax, thanks for the request. Do you want to implement this yourself? If not, then I would take over 😊

**Comment by 0rax** [comment]
Hey @HallerPatrick, you can go for it, I don't have much Rust experiences and, to be honest, don't have much time to learn and tinker right now.

Thanks a lot for your consideration :smile:

**Comment by HallerPatrick** [comment]
Alright, I got a little bit creative! I was not using the image provided by @0rax cause the round corners are not working to well in ascii. So I used the more "sharp" version.

Which one (if even) you like better? @o2sh @spenserblack @0rax 

No. 1:
![Screenshot 2021-07-13 at 19 05 38](https://user-images.githubusercontent.com/22773355/125495699-d93ae16c-2386-41d7-a9fb-a0e02f4d6e98.png)

No. 2:
![Screenshot 2021-07-13 at 19 06 56](https://user-images.githubusercontent.com/22773355/125495755-988f16c5-4848-48ae-97ac-eb2bc33da37a.png)

**Comment by 0rax** [comment]
Wow nice ! It works really well with those sharp corners and aspect ratio (which match the older logo design before Google redesigned not so long ago). I'm sure nobody would mind it. 

As per both designs, I do have a small preference for number 2 here.

**Comment by o2sh** [comment]
Looks great @HallerPatrick :tada: 
it will just require some slight retouching to make it perfectly symmetrical - I'll show you where in the PR if needs be.

**Comment by HallerPatrick** [comment]
> Looks great @HallerPatrick 🎉
> it will just require some slight retouching to make it perfectly symmetrical - I'll show you where in the PR if needs be.

Please go ahead! :)

**Comment by o2sh** [comment]
80af6ec

![protobuf](https://user-images.githubusercontent.com/13710835/125649588-6be3b4cb-6014-4e30-9fed-b9faa9cbbef1.png)

**Comment by o2sh** [comment]
80af6ec  254498e

![protobuf2](https://user-images.githubusercontent.com/13710835/125658124-dcd41bc0-f24c-4eb3-9618-fa797413b1ae.png)

**Comment by HallerPatrick** [comment]
> [80af6ec](https://github.com/o2sh/onefetch/commit/80af6ec54b34fa2847984775f44896a584cb1a88) [254498e](https://github.com/o2sh/onefetch/commit/254498e36fbd14fc4cda617d9e50488b5e5efbbf)
> 
> ![protobuf2](https://user-images.githubusercontent.com/13710835/125658124-dcd41bc0-f24c-4eb3-9618-fa797413b1ae.png)

Clean!

**Comment by o2sh** [comment]
final version:

![protobuf3](https://user-images.githubusercontent.com/13710835/125693566-639840d4-d28f-4df2-9c78-d443083bd8e2.png)
