### ISSUE TITLE
Automate documentation of language count

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#493]
Currently, the READMEs report "over 50 languages" are supported. While this is true, it's a bit on the low side to be honest. Here is the current language count:
```console
$ onefetch --version
onefetch 2.10.2
$ onefetch --languages | wc -l
76
```
It might be possible to create an Action to take the output of `cargo run -- --languages | wc -l` and parse the result into the READMEs, to keep the count up-to-date.
Although, if the language count is kept up-to-date in the READMEs, all of them will have to be updated to no longer have "more than", "以上", etc.

Alternatively, instead of updating the text of the README, perhaps a badge with automated updates can be added to show the most up-to-date supported languages count.

**Comment by o2sh** [comment]
Sounds interesting :thinking:, I like the second option better with a badge that would redirect to the [wiki](https://github.com/o2sh/onefetch/wiki/language-Support), for simplicity we could stick it only to the English README.md.

If this is doable via GH Actions: (IMO) a trigger on release would be sufficient.

**Comment by spenserblack** [comment]
I agree with the trigger on release.
I'm thinking something along the lines of:
1. get language count
2. `curl` a badge from shields.io (example: ![badge](https://img.shields.io/badge/supported%20languages-70-blue)) to a file like `supported-languages.svg`
3. use `![supported languages](./path/to/supported-languages.svg)` in the README(s)

I'll try it out and make a PR later
