### ISSUE TITLE
Reduce the Commit Hash to 7 characters

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#50]
This one should be simple enough, we would like to shorten the commit hash to only 7 characters: 

![onefetch-commit-hash](https://user-images.githubusercontent.com/13710835/66190414-34f82b80-e68c-11e9-9151-237b9713c5a8.png)

64fc1d8e34d4f7cefa7a60a83125a7d6f199a --> 641fc1d

Good luck 🥇

**Comment by arvidboivie** [comment]
I'll have a look at it :)
