### ISSUE TITLE
Document minimum Rust version?

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#525]
There have been a few issues caused by incompatible Rust versions (#183 and #128). It might be helpful if the minimum required Rust version was documented somewhere.

I wrote [this action](https://github.com/spenserblack/actions-msrv) recently (it's just a wrapper around [cargo-msrv](https://github.com/foresterre/cargo-msrv)), which might be helpful if we decide to try this.

**Comment by o2sh** [comment]
Absolutely @spenserblack
Adding the [`create-msrv-badge`](https://github.com/spenserblack/actions-msrv/blob/master/examples/.github/workflows/examples.yml) job to the CD pipeline sounds like a great idea to me :+1:
