### ISSUE TITLE
Use time crate instead of chrono

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#526]
#516 #515 

The `chrono` crate does not seem to be [actively maintained](https://www.reddit.com/r/rust/comments/qamgyh/is_the_chrono_crate_unmaintained/hh6h36h/).

We may have to try and replace the `chrono` crate with `time` where possible.
As a result, we will have to port some of [chrono-humanize](https://gitlab.com/imp/chrono-humanize-rs)'s logic and integrate it into onefetch inside a `time.rs` module.

**Comment by HallerPatrick** [comment]
How about using [humantime](https://github.com/tailhook/humantime) as an alternative für `chrono-humanize`?  It states that it is based on `time`. 

I could look into it to see if it worsk how we want it / how `chrono-humanize` did it.

**Comment by o2sh** [comment]
Actually, humantime is a _"A parser and formatter for **std::time**::{Duration, SystemTime}"_ which only relies on `time` (and `chrono`) for benchmarks and unit tests. This makes it a perfect candidate for what we intend to do.

So yeah, fingers crossed 🤞

**Comment by HallerPatrick** [comment]
You are right. Its only good for parsing human time. I misread that.

@o2sh do you know why we apply the offset for timezones to the elapsed time till creation [here](https://github.com/o2sh/onefetch/blob/689a0ab8ed92fad7743a72775d709ae43bc84718/src/info/repo.rs#L339-L355)? And why it is `west`. As long as the repo to display is not created hours ago, those +-5 hours are not relevant. But e can imitate this by adding the required offset as hours if needed. 
What seems harder is to humanize the duration. I looked into the source of `chrono-humanize` and its not too complicated, but also not trivial enough to just be added to the `onefetch` IMO. 

Making a new crate: `humanize-time` would be relatively easy to port from `chrono-humanize`, but is still some work.

I think about making this a new repo/crate.

**Comment by o2sh** [comment]
> @o2sh do you know why we apply the offset for timezones to the elapsed time till creation here? And why it is west. As long as the repo to display is not created hours ago, those +-5 hours are not relevant.

If I'm not mistaken, this logic was added in one of your PR #341

> What seems harder is to humanize the duration. I looked into the source of chrono-humanize and its not too complicated, but also not trivial enough to just be added to the onefetch IMO.

Either that or just add a `time.rs` module inside the project. Whatever works best for you :+1:

**Comment by HallerPatrick** [comment]
> > @o2sh do you know why we apply the offset for timezones to the elapsed time till creation here? And why it is west. As long as the repo to display is not created hours ago, those +-5 hours are not relevant.
> 
> If I'm not mistaken, this logic was added in one of your PR #341
Haha, well of course it was me. I think this is something that can be removed. 
> 
> > What seems harder is to humanize the duration. I looked into the source of chrono-humanize and its not too complicated, but also not trivial enough to just be added to the onefetch IMO.
> 
> Either that or just add a `time.rs` module inside the project. Whatever works best for you 👍
Yeah, I will first try a implementation in this module.

**Comment by spenserblack** [comment]
Closed by #533
