### ISSUE TITLE
'Generate MSRV Badge ' workflow times out 

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#544]
The 'Generate MSRV Badge' has been [timing out](https://github.com/o2sh/onefetch/actions/workflows/msrv-badge.yml) systematically since the last release.

**Comment by spenserblack** [comment]
I'll look into this. Looking into `cargo-msrv`, it looks like the `--bisect` search isn't as thoroughly tested, so I wonder if that's causing the timeout. A linear search is theoretically slower, though (but neither should be 6+ hours IMO).

**Comment by spenserblack** [comment]
Yeah, just tried both default behavior and `--bisect` with `cargo msrv` on onefetch and it seemed to hang up on Rust `1.42.0` for some reason. I'll update this to just be linear.
The linear search actually isn't much of a time loss either, considering that onefetch targets a fairly high Rust version.
