### ISSUE TITLE
Additional info about Authors (Contributors)

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#55]
Current display:

![DeepinScreenshot_select-area_20191001200044](https://user-images.githubusercontent.com/13710835/66268961-395e4900-e832-11e9-932f-1bbafac50687.png)

In addition to their names, we would like to display the number of commits (number and percentage of total commits), in the same spirit of [git summary](https://github.com/tj/git-extras/blob/master/Commands.md#git-summary):

![DeepinScreenshot_select-area_20191006121421](https://user-images.githubusercontent.com/13710835/66269016-db7e3100-e832-11e9-9214-cba1e6acf39a.png)

:100: :1st_place_medal:

**Comment by WillyChen123** [comment]
Hi, I would like to work on this issue.
Could you please tell me what the format is?
Is the same as the picture?
Thank you. 😊

**Comment by o2sh** [comment]
You have total freedom, display it the way you think is best :100:

**Comment by WillyChen123** [comment]
OK, Thank you.
