### ISSUE TITLE
Add number of files to Repository size

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#56]
We would like to display the number of files present in a repo.

That information should be displayed along side the "Repository size", as such:

**_Repository size: 31.63 MiB (307 files)_**

You can use  `git-ls-files`  to get the list of files and then count it.

:100: :1st_place_medal:

**Comment by Vipul-Bajaj** [comment]
Hi Ossama, I can take this up.

**Comment by Vipul-Bajaj** [comment]
Hi,
What should be the output if the size is unknown??
Should be something like this : **?? (?? files)** or **??**

**Comment by o2sh** [comment]
Well, if both infos are unknown --> ??
If only the size is unknown --> ?? (X files)
If only the number of files is unknown --> X MiB

**Comment by Vipul-Bajaj** [comment]
Thanks
