### ISSUE TITLE
Svelte logo probably needs to be changed

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#572]
So I ran `onefetch` on a Svelte project and noticed something: the current logo is whitespace (renders as black on a dark terminal) surrounded by a white shape kind of like a circle, with a red background. I did a double-take when I saw the ASCII. With the combination of a black logo, white circle, and red background, it has a pretty strong resemblance the Nazi flag IMO. At least on a terminal that doesn't support true color. It wasn't really noticeable in the initial contribution since the screenshot had low contrast colors.

It probably needs some sort of change, like filling in the whitespace with red or removing the red background.

**Comment by o2sh** [comment]
That's a good point. we could switch to this color palette:

![7exmJEg4_400x400](https://user-images.githubusercontent.com/13710835/151658433-47db235e-941a-4da1-b80b-0f68e356cb32.png)

**Comment by spenserblack** [comment]
Yeah, I think that looks good. It's pretty close to Svelte's current logo, too.
