### ISSUE TITLE
Feature request: macOS support

### ISSUE THREAD

**Issue by shadows1003929** [o2sh/onefetch#597]
Please add a macOS dmg or compile instructions

**Comment by o2sh** [comment]
Hi @shadows1003929, you can install onefetch via brew or MacPorts, more info in the [wiki](https://github.com/o2sh/onefetch/wiki/Installation#macos)

You can also take a look at [this](https://github.com/o2sh/onefetch/wiki/Installation#build-from-source), if you want to build from source
