### ISSUE TITLE
Change coloring dependency

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#605]
Not something that needs to be done right now IMO, but something we might want to do eventually. `colored` hasn't been updated in a while, and may not be maintained anymore.

I'm creating this issue to document potential alternatives should we ever decide to switch to a different dependency (this isn't a definitive list, I'll add more as a find them 🙂)

- [`owo-colors`](https://github.com/jam1garner/owo-colors)

**Comment by o2sh** [comment]
`owo-colors` seems like a great candidate for this with very low - to no - efforts on our part.
