### ISSUE TITLE
[QUESTION] Should onefetch report remote data?

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#63]
Hello! Should onefetch report data from the remote repository (number of stars, number of issues, etc.)? Or is onefetch planned to focus mainly on local repository data?

**Comment by o2sh** [comment]
Hi @spenserblack ,

As it requires the use of an [API](https://api.github.com/repos/o2sh/onefetch ) to get these additionnal infos, it would make onefetch network dependant....

Not sure if it's such a good idea

**Comment by spenserblack** [comment]
Understood, thanks!
