### ISSUE TITLE
Add WinGet as an installation option

### ISSUE THREAD

**Issue by russellbanks** [o2sh/onefetch#638]
It would be nice if this could be installed via [WinGet](https://github.com/microsoft/winget-cli)

**Comment by o2sh** [comment]
Sorry for the late answer. I'll take care of it and report back once it's done.

**Comment by russellbanks** [comment]
Hi, I've looked into WinGet a lot since I made this issue and the reason I closed this issue was WinGet currently does not support zip files, only installers:

> Note: At this time installers must either be MSIX, MSI or .exe application installers. Standalone or portable executables, compressed .zip files, and fonts are not currently supported.

Therefore, it looks like this project would have to compile a binary that is installable in order to package it on WinGet.

**Comment by o2sh** [comment]
That's right, but we should be able to create a windows installer using [Inno Setup](https://jrsoftware.org/isinfo.php) and make it part of the CD pipeline.

**Comment by spenserblack** [comment]
Coincidentally, I stumbled on [microsoft/setup-msbuild](https://github.com/microsoft/setup-msbuild) after seeing it used [in this workflow](https://github.com/cli/cli/blob/a0a9099037ab91e10fc389b4cd07c5fe7ed1bd5d/.github/workflows/releases.yml#L133). Don't know much about making Windows installers, but it might be useful.

**Comment by o2sh** [comment]
I found a rust project that does exactly what we want: it calls a [shell script](https://github.com/wez/wezterm/blob/6f0888cd7dda052137d3f304a5d7a95dea51bd8c/ci/deploy.sh#L100) from ci and it uses `iscc.exe` (Inno Setup) with an [iss file](https://github.com/wez/wezterm/blob/main/ci/windows-installer.iss) to generate the installer.

**Comment by o2sh** [comment]
Onefetch 2.12.0 can now be installed using winget 🎉 

I have updated the [wiki ](https://github.com/o2sh/onefetch/wiki/Installation) with a new entry for winget and #668 should take care of generating a new installer on release.

> If it's helpful, I use the [Winget Releaser](https://bittu.eu.org/docs/wr-intro) GitHub action in my repositories that runs on release and will automatically create a pull request on WinGet packages. 

Indeed, this would be the last task to have a fully automated winget deployment process..

> I'm happy to make a PR for this if it would be beneficial.

That would be great @russellbanks 🚀

**Comment by russellbanks** [comment]
> Onefetch 2.12.0 can now be installed using winget 🎉

Just installed and working great, thank you!

>That would be great @russellbanks 🚀

PR incoming!
