### ISSUE TITLE
Ignore some dirs while counting rows

### ISSUE THREAD

**Issue by F0rzend** [o2sh/onefetch#649]
In golang i use vendor directory with requirements.
In onefetch I don't want to see the number of lines inside dependencies.

It would be cool if you could add the ability to skip some directories when counting lines.
It would be even cooler if the vendor directory for GoLang was ignored by default

**Comment by spenserblack** [comment]
`onefetch --exclude vendor` should work.

>It would be even cooler if the vendor directory for GoLang was ignored by default

Since `onefetch` uses [tokei](https://github.com/XAMPPRocky/tokei), the vendor directly should be ignored as long as it's in either your `.gitignore` or a `.tokeignore` file.
