### ISSUE TITLE
Typescript labeled as C++

### ISSUE THREAD

**Issue by harjotgill** [o2sh/onefetch#665]
### Expected Behavior

Screenshot from Github
<img width="372" alt="Screen Shot 2022-05-12 at 9 12 25 AM" src="https://user-images.githubusercontent.com/18579817/168121002-ae1a601b-966a-4e88-8646-2c5a811b61fe.png">

### Actual behavior

Screenshot from onefetch

<img width="892" alt="Screen Shot 2022-05-12 at 9 12 08 AM" src="https://user-images.githubusercontent.com/18579817/168121063-85a00b23-b99d-4690-be11-8b2828fa234d.png">

**Comment by o2sh** [comment]
Good Idea, maybe I can add  a "Duplicates" Section in the new `bug_report.yml` issue form that will mention #26 - and possibly other recurring issues.
