### ISSUE TITLE
Generate MSRV badge failed

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#670]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

The last execution of the GitHub Action that generates the MSRV badge [failed](https://github.com/o2sh/onefetch/runs/6507064684?check_suite_focus=true) with the following message:

`Unable to find a Minimum Supported Rust Version (MSRV).`
 
### Expected behavior 🤔

I ran `cargo msrv` locally and the msrv should be 1.60.0.

### Steps to reproduce 🕹

Run the GitHub action manually.

**Comment by spenserblack** [comment]
I think that perhaps the version of `cargo-msrv` installed by the action needs to be updated. Currently it installs `~0.12`. With the latest update to `git-repository`, the MSRV might have been bumped above a version that `cargo-msrv@~0.12` supports. I'll have to see if I can recreate this with a local install of `cargo-msrv`.

**Comment by spenserblack** [comment]
Somewhat related: `Cargo.toml` can now have a [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) (starting with 1.56), which we may want to add.

**Comment by spenserblack** [comment]
https://github.com/spenserblack/onefetch/commit/ea9fbbe03074c01cd9476eaac7b868d7776712e9
