### ISSUE TITLE
Restrict wiki editing to collaborators only

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#681]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Random GitHub users are able to edit the wiki.

### Expected behavior 🤔

They shouldn't be able to do that 😆

**Comment by spenserblack** [comment]
There should be a setting "Restrict editing to collaborators only"

**Comment by o2sh** [comment]
done 👍 

<img width="623" alt="Screenshot 2022-06-12 at 14 08 11" src="https://user-images.githubusercontent.com/13710835/173232363-944d4105-c599-49f0-820b-f0f96cf3ba82.png">

**Comment by spenserblack** [comment]
Just reversed https://github.com/o2sh/onefetch/wiki/Installation/_compare/dd6be88%5E...dd6be88 🙂

**Comment by o2sh** [comment]
> Just reversed https://github.com/o2sh/onefetch/wiki/Installation/_compare/dd6be88%5E...dd6be88 🙂

:scream:

**Comment by quazar-omega** [comment]
Hey, I'd like to commit some changes to my script in the wiki, but I can't find a way to create a pull request for it.
Can you point me in the right direction to do that?

Thanks for featuring me btw, I noticed it just now and I felt I had to make some adjustments since it's officially in your project.

**Comment by spenserblack** [comment]
@quazar-omega Funny, I literally just created [this repo](https://github.com/spenserblack/actions-wiki) before viewing your comment :laughing:

Assuming we don't want to wait for me to write the initial implementation, [this action](https://github.com/SwiftDocOrg/github-wiki-publish-action) looks promising (but unmaintained). @o2sh What do you think?

TBH we don't even need an action (I was going to write it as a pure YAML composite action) if we wanted to do this. Probably something like this:
```bash
cd wiki-directory
git init
git remote add origin https://github.com/o2sh/onefetch.wiki.git
git fetch origin
git reset origin/master
git add --all
git commit -m "Update wiki"
git push -u origin master
```

**Comment by quazar-omega** [comment]
Oh, haha what a coincidence! That action looks pretty good!
Either way you want to tackle this, I think I'll be able to wait to publish my changes to do so properly, I'll have to keep my hands tied in the meantime (  ⌣̀_⌣́)

I think we can move this conversation to a new issue at this point

**Comment by quazar-omega** [comment]
#925
