### ISSUE TITLE
Set Custom colors via flag

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#69]
Currently, the colors used for each language are hard coded in a vector:
`Language::Clojure => vec![Color::BrightBlue, Color::BrightGreen]`

We would like to give the user the possibility to set his own colors by passing a flag:

`onefetch --ascii_colors 1 2 3 4 5 6`

Inspired from a neofetch's [feature](https://github.com/dylanaraps/neofetch/wiki/Custom-Ascii-art-file-format) , it would be helpful to add a visual marker at the bottom right to tell the user the color order (1: red, 2: green...) as such :

![DeepinScreenshot_select-area_20191012000557](https://user-images.githubusercontent.com/13710835/66691199-18f41b80-ec84-11e9-9bc3-981ef22075c8.png)

This feature is for the brave only :1st_place_medal:

**Comment by spenserblack** [comment]
Sounds fun! Can I try this one?
