### ISSUE TITLE
Kindly please add support for the org language

### ISSUE THREAD

**Issue by Jorghy-Del** [o2sh/onefetch#702]
### Language Name 🖊

The name of the language is org. It is a simple plain text file format used with emacs. tokei has support for it.

### Logo 📷

![image](https://user-images.githubusercontent.com/91205677/179403822-6a0cccca-07b4-47fa-8fce-d07b794e2ba2.png)

### Upstream support ✅

- [X] Does tokei already support the language in question?

**Comment by spenserblack** [comment]
Is it different from this?
https://github.com/o2sh/onefetch/blob/debd4538591d0e7a9f0d24286a267ceb157d9ce0/languages.yaml#L1497-L1519

**Comment by Jorghy-Del** [comment]
Looks ok.
