### ISSUE TITLE
Disable info line from appearing in the output

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#73]
We would like to allow users  to disable one (or many) info line(s) from appearing in the output via a command line flag:

`onefetch --disable size version`

:100:

**Comment by ktsuench** [comment]
I'd like to take a crack at this one :)

**Comment by mstruebing** [comment]
I'll give it a try.

**Comment by mstruebing** [comment]
Oh, sorry, I had this tab open and only recently refreshed it and saw you want to do it :(

**Comment by ktsuench** [comment]
That's alright, I could probably learn from how you do it. I don't have much experience with Rust :)
