### ISSUE TITLE
[Code organization] Split main.rs into modules

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#77]
As suggested by @mstruebing in #70, 
It's time to split the main.rs file into multiple files/modules.

Feel free to re-organize the code in a way that improves the navigation inside the project overall.

Thx :100: :1st_place_medal:

**Comment by mstruebing** [comment]
I think I will try that one.

**Comment by o2sh** [comment]
Don't hesitate to ask for help if need be :smile_cat:
