### ISSUE TITLE
Yaml support does not work

### ISSUE THREAD

**Issue by zoenglinghou** [o2sh/onefetch#823]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I have a repo of many ansible playbooks in `yaml` format. When I run `onefetch`, none of the `yaml` files are detected.

### Expected behavior 🤔

`yaml` files are picked up and counted in statistics.

### Steps to reproduce 🕹

1. Onefetch 2.12.0 from `nixpkgs`
2. Run onefetch in repo with `yaml` files

**Comment by spenserblack** [comment]
By default we show programming (e.g. Rust) and markup (e.g. HTML), and hide prose (e.g. Markdown) and data (e.g. YAML).

Please look at the `-T`/`--type` option.

Closing for now, but let us know if you need any more help 🙂
