### ISSUE TITLE
Support for Ubuntu 22.04 jammy from ppa

### ISSUE THREAD

**Issue by pietryszak** [o2sh/onefetch#825]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Package for jammy from ppa is not avaible.
![image](https://user-images.githubusercontent.com/45850093/196010172-4c7a0bdb-e165-4680-88c5-df87cb54d06a.png)

### Expected behavior 🤔

Package for Jammy in ppa :)

### Steps to reproduce 🕹

sudo add-apt-repository ppa:o2sh/onefetch
sudo apt-get update
sudo apt-get install onefetch

**Comment by o2sh** [comment]
Hi @pietryszak,

I've just published a new package for Jammy to launchpad:

![image](https://user-images.githubusercontent.com/13710835/196818790-f5cf2070-92c8-4520-a9c0-f5ad98c51caa.png)

Don't forget to `sudo apt-get update` before trying again.

**Comment by o2sh** [comment]
Sorry for the late answer @pietryszak 
The v2.12.0 of onefetch fails to build on launchpad. This is true for fall Ubuntu releases. 

```
Caused by:
  process didn't exit successfully: `/<<PKGBUILDDIR>>/target/release/build/zstd-sys-f6728baed230943c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Folder 'zstd/lib' does not exists. Maybe you forgot to clone the 'zstd' submodule?',
```

This is caused by zstd which is a dependency of [askalono](https://github.com/jpeddicord/askalono) that we use for license detection. More info on the issue -> https://github.com/rust-lang/cargo/issues/10532

The next release should fix this problem. In the meantime you could install onefetch using [snap](https://github.com/o2sh/onefetch/wiki/Installation#snap).

I'll keep this issue open until the next release resolves it

**Comment by pietryszak** [comment]
> I'll keep this issue open until the next release resolves it, hopefully🤞 

Ok, thank you for information.

**Comment by o2sh** [comment]
Should be good now, the latest  release (v2.13.1) was published successfully to launchpad:

![image](https://user-images.githubusercontent.com/13710835/197352894-563d703f-ce52-4f8f-b8fe-75430731e7fc.png)

Don't forget to `sudo apt-get update` before `sudo apt-get install onefetch`

I'll let you close this issue if everything works as expected on your side.

**Comment by pietryszak** [comment]
> Should be good now, the latest release (v2.13.1) was published successfully to launchpad:
> 
> ![image](https://user-images.githubusercontent.com/13710835/197352894-563d703f-ce52-4f8f-b8fe-75430731e7fc.png)
> 
> Don't forget to `sudo apt-get update` before `sudo apt-get install onefetch`
> 
> I'll let you close this issue if everything works as expected on your side.

It's working and now working at once. App is downoaded and installed but when I try to startup i have error

![image](https://user-images.githubusercontent.com/45850093/197359701-2904abe8-e14b-43b4-a9b7-4eebd1409a2a.png)

**Comment by o2sh** [comment]
You need to be running onefetch inside a Git repository (or by giving it a path to the repo `onefetch <path-to-repo>`)

cf. @spenserblack 's comment for more details --> https://github.com/o2sh/onefetch/issues/826#issuecomment-1280162669

**Comment by pietryszak** [comment]
> You need to be running onefetch inside a Git repository (or by giving it a path to the repo `onefetch <path-to-repo>`)
> 
> cf. @spenserblack 's comment for more details --> https://github.com/o2sh/onefetch/issues/826#issuecomment-1280162669
> 
> Another example:
> 
> ```sh
> git clone https://github.com/o2sh/onefetch
> cd onefetch
> onefetch
> ```

I think it's only when install onefetch by cargo metod or build from source not when ppa method.
So what's is idea of ppa when i need to do extra steps.

**Comment by pietryszak** [comment]
> You need to be running onefetch inside a Git repository (or by giving it a path to the repo `onefetch <path-to-repo>`)
> 
> cf. @spenserblack 's comment for more details --> https://github.com/o2sh/onefetch/issues/826#issuecomment-1280162669
> 
> Another example:
> 
> ```sh
> git clone https://github.com/o2sh/onefetch
> cd onefetch
> onefetch
> ```

Ok working. Thanks

**Comment by o2sh** [comment]
There is no extra steps, I was just giving you an example on how to make use of `onefetch`.

Now that you have installed onefetch, you just need to find a valid git repository to use it on.

**Comment by pietryszak** [comment]
Checked. Working in Ubuntu 22.04

**Comment by pietryszak** [comment]
@o2sh  Thanks for help. Time to do same think for 22.10 ;)

**Comment by o2sh** [comment]
![image](https://user-images.githubusercontent.com/13710835/197360684-74c92415-aa78-49fb-9331-17763c9deaef.png)

Done 😄

**Comment by pietryszak** [comment]
> ![image](https://user-images.githubusercontent.com/13710835/197360684-74c92415-aa78-49fb-9331-17763c9deaef.png)
> 
> Done smile

Great :)
