### ISSUE TITLE
Keep the same spacing between the ASCII art and the info lines

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#83]
As of today, the distance/spacing between the ASCII logo and the info bloc is quite inconsistent among the different languages:

* Perl (too much spacing and presence of left indentation):

![61182863-f91f6e00-a628-11e9-9856-8e9b3e1b928f](https://user-images.githubusercontent.com/13710835/66746035-fd099900-ee80-11e9-80ff-394efe0b7a6c.png)

* Swift (no spacing and left indentation):
 
![56481406-0a088980-64e9-11e9-9e81-09f00b2414cb](https://user-images.githubusercontent.com/13710835/66745430-32ad8280-ee7f-11e9-9146-ea59506d4375.png)

The idea would be too have the same spacing for all and no left indentation.

💯 🥇

**Comment by Vipul-Bajaj** [comment]
Hi Ossama, I can take this up.
