### ISSUE TITLE
Output is terrible on windows

### ISSUE THREAD

**Issue by kjeremy** [o2sh/onefetch#86]
This is what it looks like on `rust-analyzer`.

```
                                         [1;37mProject: [0mrust-analyzer
[37m             `  :y.`yy`.y:  `[0m            [1;37mHEAD: [0m0cce2bc (master, origin/master, origin/staging)
[37m         -``MNsNMMNNNNMMNsNM``-[0m          [1;37mVersion: [0mguide-2019-01
[37m      ` -MMNMMMMNNm``NNNMMMMNMM- `[0m       [1;37mCreated: [0m1 year, 10 months ago
[37m     `NNNMMMdo:` `+md/  `:odMMMNNN`[0m      [1;37mLanguages: [0mRust (96.38 %) TypeScript (3.57 %) JavaScript (0.04 %)
[37m   -ssNMMNo.                .oNMMNss-[0m               Shell (0.01 %)
[37m   `mMM[0m[91mMMNmmmmmmmmmmmmmmmdy+`[0m[37m `sMMMm`[0m    [1;37mAuthors: [0m40% Aleksey Kladov 2128
[37m `mMMM[0m[91mMMMMMMMMMMMMMMMMMMMMMMN/[0m[37m  hMMMMm`[0m  [1;37m         [0m25% bors[bot] 1313
[37m -oMN-:Ny:[0m[91mmMMMMMm    oNMMMMMm[0m[37m oN::MMo-[0m   [1;37m         [0m5% Florian Diebold 296
[37m.yMMMhhh+ [0m[91mdMMMMMd:::::+mMMMMN/[0m[37m odyhMMMy.[0m [1;37mLast change: [0m4 hours ago
[37m-sNMMy    [0m[91mdMMMMMMMMMMMMMMMMs`[0m[37m    `yMMNs-[0m [1;37mRepo: [0mhttps://github.com/rust-analyzer/rust-analyzer.git
[37m-sNMMy    [0m[91mdMMMMMNyyyydMMMMMMy[0m[37m   .odMMNs-[0m [1;37mCommits: [0m5227
[37m.yMMMm   [0m[91mdMMMMMh     +MMMMMM+[0m[37m  sMMMMMy.[0m  [1;37mLines of code: [0m61872
[37m -oMMM[0m[91mMMMMMMMMMMMMMM+  mMMMMMMMMMM[0m[37mMMMo-[0m  [1;37mSize: [0m18.96 MiB (889 files)
[37m `mMMM[0m[91mMMMMMMMMMMMMMM+  :NMMMMMMMMM[0m[37mMMMm`[0m  [1;37mLicense: [0mApache License 2.0
[37m   `mMMMm               `-:o+:/mMMMm`[0m
[37m   -ssNMMMyomo            smohMMMNss-[0m
[37m     `NNNMs+mN/-`      `-/Nd/yMNNN`[0m
[37m      ` -MMNMMMMMNmmmmNMMMMMNMM- `[0m
[37m         -``MNsNMMNMMNMMNsNM``-[0m
[37m            `  :y.`yy`.y:  `[0m
```

**Comment by spenserblack** [comment]
Looks like this might be fixed by updating `colored` to 1.8, which includes support for the Windows build target.

**Comment by kjeremy** [comment]
That did not fix it locally. I can run with NO_COLOR=1 in my environment and that at least gets readable output.

**Comment by spenserblack** [comment]
Which version of Windows is this? Just ran it on W10 (without updating crate) and it works. This is probably related to mackwic/colored#59.

**Comment by kjeremy** [comment]
1809 Build 17763.805

**Comment by kjeremy** [comment]
The examples from the `colored` repo work

**Comment by kjeremy** [comment]
Even on tag v1.6.1 so it might not be a `colored` thing specifically.

**Comment by o2sh** [comment]
I'm not sure

**Comment by kjeremy** [comment]
Great that fixed it!

**Comment by o2sh** [comment]
@kjeremy can you give it another try? I've just pushed an update in the light of @spenserblack remarks.

**Comment by o2sh** [comment]
I'm confused, did my commit fixed it ?

**Comment by kjeremy** [comment]
Yes your commit fixed it :)

**Comment by spenserblack** [comment]
> Great that fixed it!

:tada: 
Not sure why it worked on my W10 machine before the commit (older version, too) :thinking:

**Comment by o2sh** [comment]
Did you run the .exe or just via `cargo run` ?

Anyway, I'm not sure my commit is the best way to handle this issue.
I didn't use `control::set_virtual_terminal(bool)`

========================

Thanks again for the help @spenserblack .

I added you as a contributor of the repo. You can merge pull requests when you feel like it's of enough quality and commit to the repo directly 👍

**Comment by o2sh** [comment]
The output is broken again 😢 

![image](https://user-images.githubusercontent.com/13710835/67620455-481f9680-f807-11e9-83b5-be532413bbbb.png)

**Comment by spenserblack** [comment]
😱 
I didn't really have a chance to test it on Windows (since the colors worked *before* the fix for me for some reason, still not sure why).
Did I perhaps reverse the logic [here](https://github.com/o2sh/onefetch/blob/f5296f2bd338c9060017438bef5ca28b7823142a/src/main.rs#L83) when getting it to compile on Linux?

**Comment by kipters** [comment]
Did you test on both the old conhost.exe console and the new Windows Terminal? Maybe there's a difference there

**Comment by spenserblack** [comment]
Just pushed up a new commit which should fix the issue. Was able to replicate behavior on my Windows machine.
