### ISSUE TITLE
Support shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [o2sh/onefetch#864]
### Summary 💡

```sh
❯ onefetch -<TAB>
option
-a                    <LANGUAGE>
--ascii-colors        <X>...
--ascii-input         <STRING>
--ascii-language      <LANGUAGE>
--color-resolution    <VALUE>
-c                    <X>...
-d                    <FIELD>...
--disabled-fields     <FIELD>...
-e                    <EXCLUDE>...
--email               Show the email address of each author
-E                    Show the email address of each author
...
```

### Motivation 🔦

<https://jmtirado.net/shell-completion-with-cobra-and-go/>
<https://github.com/cli/cli/blob/cf4b73ff958b272cf3c9c0cf9351459f76b793a0/pkg/cmd/completion/completion.go>

**Comment by spenserblack** [comment]
```bash
# generate completions
onefetch --generate <SHELL>
```
e.g. `onefetch --generate bash`

Does this work for you? Do you use a shell we don't support? (You can see all supported shells in the `onefetch --help` message).

**Comment by Freed-Wu** [comment]
Thanks!

**Comment by spenserblack** [comment]
(moving to "not planned" since we already support completions)

**Comment by Freed-Wu** [comment]
You are welcome. I recommend adding the information that this program support completions to documents in order to let packager know this thing.

**Comment by mhmdanas** [comment]
In general, I think it's a good idea to have a guide for packagers.
