### ISSUE TITLE
OneFetch 2.13.2 DisplayVersion written with "v"

### ISSUE THREAD

**Issue by russellbanks** [o2sh/onefetch#868]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

OneFetch 2.13.2 writes the DisplayVersion of `v2.13.2`. This should really be `2.13.2`. This causes WinGet to show OneFetch as always needing an update:

![WindowsTerminal_C0oxwF1DmT](https://user-images.githubusercontent.com/74878137/202899313-baee5b9e-2a57-4d95-a4b1-0b0997366dd4.png)

### Expected behavior 🤔

OneFetch should write the DisplayVersion without the "v".

### Steps to reproduce 🕹

1. Install OneFetch 2.13.2.
2. See DisplayVersion written with "v" in front of it.

### Temporary solution
As a temporary solution, I can add an entry to the Onefetch manifest, and this would tell WinGet to match the manifest to that DisplayVersion:
```yaml
AppsAndFeaturesEntries:
- DisplayVersion: v2.13.2
```
Going forward, however, it would be best to remove the "v" from the DisplayVersion.

**Comment by russellbanks** [comment]
- https://github.com/microsoft/winget-pkgs/pull/89274

**Comment by spenserblack** [comment]
Perhaps this issue should be raised with the winget-releaser action? Should it trim the leading `v`?

**Comment by russellbanks** [comment]
> Perhaps this issue should be raised with the winget-releaser action? Should it trim the leading `v`?

WinGet Releaser does do this, which is why the manifest that it produces has `2.13.2` as the PackageVersion (A manifest can't/shouldn't start with 'v' in its version).

WinGet Releaser can't change what is written to registry, though, so WinGet will match the `PackageVersion` it produces to what is written to registry, meaning it will always see it as a new version:
- `2.13.2` (PackageVersion) -> `v2.13.2` (DisplayVersion in registry)

**Comment by o2sh** [comment]
Thanks a lot for reporting this issue @russellbanks and for the PR with the temporary fix 👍 

As for the definite solution, I see two options:
- Update the [Makefile](https://github.com/o2sh/onefetch/blob/d082a8336af7ab97b1711aad2b4eaf1ac7b15672/Makefile#L18), so that the version name that is passed to the installer template doesn't contain the letter "v"
- Drop the "v" in our naming convention alltogether: next version will be 2.14.0 instead of v2.14.0

**Comment by russellbanks** [comment]
I think updating the Makefile would be sufficient. Having v2.13.2 as the GitHub release is perfectly fine, but in terms of general DisplayVersion naming conventions, OneFetch does stick out a little bit having the "v" (screenshot of some versions in my Control Panel):

![explorer_xW5hw9FG5a](https://user-images.githubusercontent.com/74878137/203846035-9dc8a09a-2ded-4bde-9cdf-33b485f5a539.png)

**Comment by russellbanks** [comment]
Resolved in [2.14.1](https://github.com/o2sh/onefetch/releases/tag/2.14.1) :)
