### ISSUE TITLE
Add an icon to the onefetch installed program

### ISSUE THREAD

**Issue by russellbanks** [o2sh/onefetch#873]
### Summary 💡

This is a minor aesthetic issue in the control panel, but it would be nice if onefetch could put its logo here.

![explorer_Eukei0gZk6](https://user-images.githubusercontent.com/74878137/203847508-d57ad166-0848-4c62-b4f1-25cca28f0738.png)

**Comment by o2sh** [comment]
Absolutely, I wish I had done it from the start.

Should be good now 👍 

![image](https://user-images.githubusercontent.com/13710835/204151301-7a12f46a-f0f0-45d0-a677-0eb2a42db1f1.png)

![image](https://user-images.githubusercontent.com/13710835/204151352-1b912154-2b11-46e0-b838-b8024dba269f.png)
