### ISSUE TITLE
Fennel support

### ISSUE THREAD

**Issue by reo101** [o2sh/onefetch#875]
### Language Name 🖊

Fennel

---

https://fennel-lang.org/

Fennel is a lisp that compiles to Lua

### Logo 📷

https://git.sr.ht/~technomancy/fennel-lang.org/blob/main/logo.svg

can be seen here: https://fennel-lang.org/

### Upstream support ✅

- [X] Does tokei already support the language in question?

**Comment by spenserblack** [comment]
Duplicate of #578

While Fennel is in tokei's source code, tokei hasn't had a release with that addition, as far as I know. https://docs.rs/tokei/latest/tokei/enum.LanguageType.html

**Comment by p00f** [comment]
Tokei now has an alpha release with fennel support: https://crates.io/crates/tokei/13.0.0-alpha.0
