### ISSUE TITLE
Use `human-panic`?

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#887]
What do you think about using [`human-panic`](https://github.com/rust-cli/human-panic) for prettier panics?

In a `--release` build, this hook will change the message to
```
Well, this is embarrassing.

{{ crate_name }} had a problem and crashed. To help us diagnose the problem you can send us a crash report.

e have generated a report file at "/tmp/{{ filename }}.toml". Submit an issue or email with the subject of "{{ crate_name }} Crash Report" and include the report as an attachment.

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

The hook also generates the named crash report on a panic.

**Comment by o2sh** [comment]
I love it, very useful and easy to use. 👍

**Comment by o2sh** [comment]
with 975856d

![image](https://user-images.githubusercontent.com/13710835/205440244-be934756-303b-4ee7-86c0-cab5f47eabb9.png)

**Comment by spenserblack** [comment]
Looks great!
