### ISSUE TITLE
basic_repo.sh can actually be just a /bin/sh script

### ISSUE THREAD

**Issue by ptrcnull** [o2sh/onefetch#893]
### Summary 💡

replace the hashbang `#!/bin/bash` with `#!/bin/sh`

### Motivation 🔦

it gets rid of the dependency on bash where it's not actually needed at all

**Comment by spenserblack** [comment]
Yeah, I don't see any bash-specific syntax in those fixtures. PRs welcome. I would ask that the hashbang gets replaced in all the fixture `.sh` files instead of just one, though.

**Comment by spenserblack** [comment]
ref: [bash-isms and their alternatives](https://wiki.ubuntu.com/DashAsBinSh)
