### ISSUE TITLE
Implement logic for project Information

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#9]
Create a function that will scan a project and retrieve its information: Name, Author, Number of lines, License... 

These info are currently hardcoded in the main function...

**Comment by zxey** [comment]
As @o2sh states in #12 there are only three things left to implement:
Project name - this can be obtained from git by parsing remote origin or some similar info
Project repo - also can be parsed from git metadata
Project license - you can probabyl use [askalono](https://github.com/amzn/askalono) library to detect license of the project
