### ISSUE TITLE
Add support for CUDA source files

### ISSUE THREAD

**Issue by jtmr05** [o2sh/onefetch#901]
### Summary 💡

It seems that `.cu` source files are simply ignored currently.

**Comment by spenserblack** [comment]
Hi! Would you mind using our [new language request](https://github.com/o2sh/onefetch/issues/new/choose) template? That would help us gather more info (like whether or not we *can* add support).

**Comment by jtmr05** [comment]
done

**Comment by spenserblack** [comment]
Thanks!
