### ISSUE TITLE
Support for HolyC

### ISSUE THREAD

**Issue by DanteFalzone0** [o2sh/onefetch#91]
We should add support for HolyC and make it so that the ascii logo of HolyC looks like it's in the TempleOS font; it should probably have a cross too. And I think its colours should be yellow, white, and cyan

------------------------------

[How to add support for a new language](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#adding-support-for-a-new-language)

**Comment by o2sh** [comment]
@DanteFalzone0  Thank you for your issue!
As you know onefetch relies on tokei for language detection. I just saw [#389](https://github.com/XAMPPRocky/tokei/pull/389). So we'll just have to wait for a new release.

**Comment by DanteFalzone0** [comment]
Okay :)

**Comment by o2sh** [comment]
HolyC is now supported by tokei!

**Comment by Ferryistaken** [comment]
I'd like to have a go at this

**Comment by Ferryistaken** [comment]
I've made a pull request #313
