### ISSUE TITLE
Enable pull requests for the wiki

### ISSUE THREAD

**Issue by quazar-omega** [o2sh/onefetch#925]
### Summary 💡

To allow those who are not collaborators to contribute to the wiki it would be good to integrate the wiki in the main repository

### Motivation 🔦

I wanted to contribute to the wiki, but wasn't able to do so easily since GitHub doesn't have a way to make pull requests directly on the wiki repository

**Comment by spenserblack** [comment]
See comments https://github.com/o2sh/onefetch/issues/681#issuecomment-1377565749 and below for some more context.

:+1: from me because I love letting GitHub Actions do all the work :laughing:

**Comment by quazar-omega** [comment]
Yup, I guess that would be more comfortable.
Better enjoy it to the fullest before our AI overlords take over and make us execute the actions instead

**Comment by spenserblack** [comment]
https://github.com/spenserblack/actions-wiki :slightly_smiling_face:

**Comment by quazar-omega** [comment]
Great, it's done on my end as well!

**Comment by spenserblack** [comment]
#926 and #927

**Comment by o2sh** [comment]
Nice team effort, nicely done @quazar-omega and @spenserblack 🎊 🎊

**Comment by quazar-omega** [comment]
Thanks to you too for the corrections @o2sh!!  \\(^▽^)/
