### ISSUE TITLE
Add flag to disable/enable bold characters

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#95]
By default, all info_name (Project, HEAD, version, etc.) and the ASCII art are displayed in Bold.

We would like to have a command line flag to disable boldness on all characters, something like:

```
onefetch --bold off //disable bold
onefetch --bold on //enable bold (equivalent to just onefetch)
```

:100: :1st_place_medal:

**Comment by ccmetz** [comment]
@o2sh Hi, I could work on this issue

**Comment by spenserblack** [comment]
Closing since #99 has been merged.
