### ISSUE TITLE
Support ansible playbooks/roles repositories yaml

### ISSUE THREAD

**Issue by Fabiokleis** [o2sh/onefetch#969]
### Language Name 🖊

Ansible, yml, yaml

### Logo 📷

nope

### Upstream support ✅

- [X] Does tokei already support the language in question?

**Comment by spenserblack** [comment]
It looks like Ansible playbooks all have either the `.yml` or `.yaml` format, is that correct?

**Comment by Fabiokleis** [comment]
> It looks like Ansible playbooks all have either the `.yml` or `.yaml` format, is that correct?

yep

**Comment by spenserblack** [comment]
Then I don't think we can recognize Ansible as a language, at least not without replacing tokei as our tool to detect languages. [Tokei will detect all `.yml` and `.yaml` files as YAML](https://github.com/XAMPPRocky/tokei/blob/6d5d023bbf86fd3e23e8e37e1e25310402ae035d/languages.json#L1618-L1623).

When/if we replace tokei, we can consider if we want to detect Ansible playbooks as a language, but right now it's very unlikely to happen.

**Comment by Fabiokleis** [comment]
so I think it's better to recognize the repositories as .yml/.yaml anyway

**Comment by spenserblack** [comment]
Data languages (JSON, YAML, etc.) are ignored by default, but can be enabled with `-T`/`--type`. See `onefetch --help` (or view [the wiki](https://github.com/o2sh/onefetch/wiki/command-line-options)) for more details.

**Comment by Fabiokleis** [comment]
I got it, thanks
