### ISSUE TITLE
Does not look well on small terminal

### ISSUE THREAD

**Issue by pickfire** [o2sh/onefetch#980]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When running onefetch on a small terminal 80x24, it does not seemed to work well.

### Expected behavior 🤔

The image and the stuff should not overflow. Maybe less people use 80x24 nowadays but it is probably not that rare given that quite a few terminals defaults to this size when starting.

### Steps to reproduce 🕹

1. onefetch

### Additional context/Screenshots 🔦

![Screenshot_20230312_195054](https://user-images.githubusercontent.com/4687791/224542706-64f4bb67-873d-4c3a-8131-7fe806f7764b.png)

### Possible Solution 💡

Reduce the ascii image size.

**Comment by spenserblack** [comment]
Just checked what `neofetch` does, and it looks like it simply cuts off text past the right boundary of the terminal.
[`\e[?7l` seems to be the relevant escape sequence](https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L11563).

**Comment by o2sh** [comment]
We've already covered this issue in the past #327 and what came out of it is the following CLI flag:

```
  --show-logo <WHEN>
      Specify when to show the logo

      If set to auto: the logo will be hidden if the terminal's width < 95

      [default: always]
      [possible values: auto, never, always]
```

But I agree with @spenserblack, it would be better to programmatically disable line wrap with `print!("\x1B[?7l")`. Unfortunately, last time I tried I failed: https://github.com/o2sh/onefetch/issues/327#issuecomment-736880866

**Comment by spenserblack** [comment]
@o2sh Thanks for the reminder! Should we consider changing the default value of the flag from always to auto? Technically a breaking change, but it should make it less likely that this issue gets raised again.

**Comment by pickfire** [comment]
Wouldn't it be good to as well reduce the logo size?

**Comment by spenserblack** [comment]
Resizing is certainly an interesting idea, but, giving that ASCII art doesn't have many "pixels", I fear that resized ASCII art could quickly become unreadable and/or diverge from the artist's intent. For example, a resizing algorithm would very likely garble the `NASA` from [Fortran's ASCII art](https://github.com/o2sh/onefetch/blob/4bab48b7f443d92fcc60b704b5de336989b98088/languages.yaml#L716-L734).

**Comment by o2sh** [comment]
>Wouldn't it be good to as well reduce the logo size?

One could create a lightweight version of 'onefetch' that emulates the style of [pfetch](https://github.com/dylanaraps/pfetch) by using smaller ASCII logos and displaying only a selection of info lines.

>Should we consider changing the default value of the flag from always to auto?

If we can't find a way to disable the line wrap properly, we may want to try that.

**Comment by pickfire** [comment]
Like detecting terminal width and shrinking the ASCII art to fit? Nope, but just find a smaller logo?

**Comment by o2sh** [comment]
Before:
<img width="689" alt="Screenshot 2023-03-18 at 15 04 32" src="https://user-images.githubusercontent.com/13710835/226110906-a8844d4a-67ff-4139-b912-c83ed4a6ef70.png">

Now:
<img width="689" alt="Screenshot 2023-03-18 at 15 06 07" src="https://user-images.githubusercontent.com/13710835/226111007-a65866df-ae63-4323-8b1a-2c65a5c0d8f2.png">

With #983, onefetch has been updated to automatically disable text wrapping on the terminal before printing its output, and then re-enables it immediately afterwards. Although this may not be the exact solution you were expecting, it ensures that the output remains readable even when the terminal window is small, without changing the output's size.

**Comment by pickfire** [comment]
![Screenshot_20230320_204230](https://user-images.githubusercontent.com/4687791/226341869-ead6e989-709b-44ee-8665-4bdf489f8644.png)

Yeah, it looks better now. I guess I can close this issue.
